### ISSUE TITLE
PLC direct input (no weighted avg data), prohibit farmer for selecting ECO for crop ins and ARC-CO for title at same time

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#1]
I think that lines 60-62 of Government Payment Data text can be removed and farmers can enter weighted average PLC yields for each crop directly (rather than having this additional step in the calculation).

For most farmers who farm the same ground every year, those weighted average PLC yields will not change from year to year and instead will get updated only every five years if/when permitted by the new Farm Bill.   However, farmers do purchase new land and change/swap/add rented acerage from year to year.   Therefore there should be a way to have different weighted average PLC yields across crop years when the functionality is expanded to allow for multiple crop years.   Also, as a practical matter, most farmers will put all their acres for a certain crop (say wheat) in the same program (say PLC).    However the farmer is not required to to put all wheat acres into the same program (say PLC) but can put some in PLC and some in ARC-CO.   So the code should allow for that possibility.    

Also recall that if a farmer uses ECO as part of the stack of insurance, that farmer MUST select PLC (and not ARC-CO) on those acres.   So if a farmer insures his corn crop with 65% RP, ECO to 86% and SCO to 90% as we have done the last few years, he must put his corn base acres in PLC.   Same is true of beans.   If a farmer uses the "stack" including ECO for beans, he must select PLC for beans.   A farmer should know this and not select ARC-CO if he is using ECO.   But at some point in the future we might want to think about a feature that prohibits that option for the farmer.   Like a message for title selection that says "if you use ECO for crop insurance for a cerain crop you must put base acres into PLC"   Basically not allowing them to make the mistake of using ECO and ARC-CO for the same crop simultaneously.   Hope that makes sense

**Comment by ddrake** [comment]
Fixed with passing tests.  Closing this issue
