### ISSUE TITLE
MYA prices shown on Title Page are not Correct in Marquis Farm Model

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#100]
I went into my Marquis Farm model to try to check to see if title payments are being computed correctly.  In this model I have price factor set to 100% for each of corn, beans and wheat and each crop is set to PLC for title.   Since I have price sensitivity at 1.0, the Estimated MYA should equal the June WASDE (July just came out today and IFBT should not be updated yet).   June WASDE MYA for corn waw $4.80, Beans was $12.10 and Wheat was $7.70.     The estimated MYA prices presented to the user on the Title tab are showing estimated MYA prices for Corn of $19.24, Beans of $135.31 and Wheat of $52.59.   Th3se are FAR FAR above what they should be and must be the result of some glitch in the data or the code.

**Comment by ddrake** [comment]
Fixed now.  There was an error in a formula (missing parens).
