### ISSUE TITLE
Testing Title Payments Reveals Problem with Estimated MYA

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#103]
I reset Marquis Farm from manual date to current date.   At Price Factor of 1.0 (set on the Grain Marketing page), Estimated MYA shows on the Title page is correct and updated to the July Wasde numbers, Corn $4.80, Beans $12.40 and Wheat $7.50.  All good.

However, when I go back over to change the Price Factor to 70% (0.7) for each crop on the Grain Marketing page, I would anticipate seeing on the Title page Estimated Sensitized MYA of Corn $3.65, Beans $9.42 and Wheat $6.38.   This is what the simplebudget tool algorithm would produce using the Post WASDE availability and the weighted average factors that are built into that calculation.   

Instead, however, on the Title page at the 70% price factor, I see Estimated Sensitized MYA for Corn at $10.27, Beans at $54.81 and Wheat at $22.13.

**Comment by ddrake** [comment]
Fixed in commit 44ca19c.
