### ISSUE TITLE
Suggested edits to Detailed Budget Page Marketed Futures Box - Wood County Farm example

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#109]
Note that currently in the Marketed Futures box that the % of Expected Bushels and % of Sensitized Bushels is the same percentage on the Wood County Farm even though I have 80% yield factor for Corn and 100% yield factor for Beans.   The Marketed Futures as % of Sensitized bushels should actually be 31.3% for Corn and 25% for Beans.    But looking at this now, I think we should have only ONE line and it should be called "% of Expected Bushels Sold" adding the world "Sold" to the title -- And this line should represent the % of Sensitized Bushels (and not Original expected Bushels).   Suggest we eliminate entirely the line that is titled "Percent of Sensitized Bushels".     What I'm suggesting is that once we put in an 80% yield factor, THAT YIELD and THOSE production bushels become (for purposes of this presentation) the EXPECTED BUSHELS and we get rid of the concept of using the ORIGINAL EXPECTED BUSHELS entirely.     So for Wood Farm it would read:
                                                     Corn                 Beans
% of Expected Bushels Sold           31.3%               25%
Avg. Futures Contract Price             $5.99               $13.93

**Comment by ddrake** [comment]
Complete in commit ce40e18.
