### ISSUE TITLE
Just tried to create a North Dakota Farm and got Server 500 error

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#111]
I just tried to create a North Dakota farm and got a server 500 error.   I went back into that farm and it seemed ok like it self healed.   But when I tried to add Farm information it gave me that Server Error (500) again.   I was just playing around to test some far away places that are on different calendars and crops that what we have been using.

**Comment by ddrake** [comment]
Should be fixed now in commit 78a9830.  I got a similar error last night for a Montana farm.  I fixed the code this morning, but forgot to update the server.  The code wasn't specifying the crop_year for insurance dates, which are looked up when a farm is created.  That bug didn't surface until I inserted records for the 2024 crop_year a couple days ago.

**Comment by KelleyDrake** [comment]
I went back to the North Dakota Farm and started to fill it out.   Everything was fine until I hit the Detailed Budget tab where I got another Server 500 error.

**Comment by ddrake** [comment]
Fixed in commit 00460e5.
