### ISSUE TITLE
Market Prices Updates Question

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#112]
I am not sure if this is intended or not.  But when I ran the North Dakota Farm today and just looked at recent market prices in the Marketing Tab, I got prices for corn and beans as of 7/18/23 (TODAY) and spring wheat as of 7/17/23 (yesterday's close).   I would have expected corn and beans to equal yesterday's 7/17/23 closes of $5.06 for corn and $3.78 for beans.    Looks like for corn and beans we did not get the close but rather an overnight trading price of $5.17 for corn and $13.90 for beans.   At this moment during the trading day off of my Interactive Brokers live screen, corn is trading at $5.3225 and beans at $13.9925.   For spring wheat we got yesterday's close and 7/17/23 is the reported date. 

It's all OK I suppose.   But I think ideally we'd probably be best working only off of actual closing prices from the preceding trading day and not using any interim or overnight futures trading pricing.

Also one other minor point.   We are calling the Minneapolis Grain Exchange (MGT).   When I went out on their site for quotes, it is referred to as "MGEX".    Not a big deal but to be accurate we should probably change the title "MGT" to "MGEX"

**Comment by ddrake** [comment]
It was an unusual situation: I made some changes to the price scripts a few days ago to deal with tickers going off the board, but there were bugs that I didn't notice until this morning.  This morning I fixed the bugs, and ran the scripts manually.  Normally the price updates happen at night and should give closing prices.  If the price shown isn't the final close, it should be automatically updated tonight.

I just changed the name to MGEX in the database.
