### ISSUE TITLE
Love the new sensitivity table formatting but need one minor change

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#113]
If you go to Marquis Farm sensitivities, note the inner box has increments of 5% and then it widens out to 10% for both price and yield.   However, Assumed Farm Yields does not follow that convention exactly.   It would be best if yield % would conform to the price % increments. 

Currently yield % goes:
40% 50% 60% 70% 80% 90% 100% 105% 110%

Suggest instead it goes:
50% 60% 70% 80% 90% 95% 100% 105% 110%

Suggest we leave the price sensitivities exactly as they are now.   

 We'll lose the 40% yield % scenario but that's OK.     It will now show a yield sensitivity range from 50% to 110% with 10% increments up to 90% and 5% increments thereafter.   I am very happy with the formatting on these tables!!

**Comment by ddrake** [comment]
Glad you like the format.  It was tricky to implement, but should be pretty easy to maintain. 
Yield factor values fixed in commit 77ad75f.
