### ISSUE TITLE
Small wierd one related to Yields Final

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#114]
For Marquis Farm I have the wheat yield input box checked so that yields are final at 105.   Everything appears to be working in the sensitivity tables.   However, when I go to the Yield and Expense Budget page, despite the fact that I have checked the yields for wheat as final on the edit, the page shows "Yields Final?    No"   when it should read "Yields Final    Yes"

**Comment by ddrake** [comment]
Fixed in commit a2c5865.
