### ISSUE TITLE
FS and DC Bean Revenue

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#115]
As we briefly discussed, the FS and DC bean revenue is calculated correctly in the Detailed Revenue computation, but those revenue figures are not flowing through to the Detailed budget page immediately below.  The FS and DC revenues should be apportioned in the bottom section the same way as the are being apportioned in the top section.

**Comment by KelleyDrake** [comment]
Also, I'm not sure how this all flows.   But the sensitivity tables should show the correct revenue apportionment between FS and DC beans.

**Comment by ddrake** [comment]
Should all be fixed as of commit 5a91ef6.
