### ISSUE TITLE
Formatting and Printing "Wishlist"

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#116]
1)	The Titles in the upper left of the page ( Integrated farm Budget Tool, My Farm Years user, Log out, Change Password) all appear in the print out.   Ideally, any print would only be the tables below.
2)	The wood Farm has only two crops.   I printed this in portrait, but we should decide whether landscape or portrait is better for all cases.   In any case I think (eventually) we would want Ctrl P to print on to two (and exactly TWO) pages in every case (biggest/widest to smallest) with pagination separating the Crop Revenue and Key Assumptions from the Budget data below.  If that means reducing the font then I think we should do that.  I suspect even with a lot of crop columns, we’ll still want it in Portrait because of the number of rows on the second of the two pages.
3)	In the Crop Revenue box I suggest removing the “CROP REVENUE CALCULATIONS” title words as they are redundant with the header “Crop Revenue” which appears above the table.
4)	I’d suggest that we insert a single empty line under Corn, FS Beans, Total to separate the titles from the Farm Yield per acre line.   I’d also suggest we underline those column headers Corn, FS Beans, Total.
5)	On the right side Key Assumptions section, if possible I’d suggest adding a line all the way across the width of the box underneath the headers Yields, Prices, Marketed Futures, Crop Insurance and Title.
6)	Per my “Issue” suggestion, in Marketed Futures suggest we eliminate the line “% of Sensitized Bushels” and instead have only one line called “% of Expected Bushels Sold”, with line actually being % of what is NOW expected (or the Sensitized Bushels), as further described in “Issues”.
7)	The Budget section in the lower half would ideally all appearing on a single second page paginated to separate it from the tables in the top half.  Shrinking fonts to make it work.
8)	Suggest we add a super header line at the very top of the table to read “Pre-Tax Cash Flow Budget” with a line underneath extending all the way from far left to far right this would be centered over all of the page.
9)	Then where it reads Budget In $000, Budget in $/acre, Budget in $/bushel.   Have that instead read “Budget ($000s)”, “Budget ($/acre)”, “Budget $/bu.)”  centered over the respective section.
10)	Then we can eliminate the title inside the box that reads “PRE-TAX CASH FLOW BUDGET”
11)	Bold and underline the column headers;  eg: Corn, FS Beans, Other, Total in each column across the page.
12)	Right justify the numbers appearing in the sensitivity tables.   They are now left justified.

**Comment by ddrake** [comment]
The sensitized values in the sensitivity tables have been right justified.
The printer css related items were moved to #62.
The detailed budget related items were moved to a new issue #117.
