### ISSUE TITLE
Problem with Variable Rent

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#122]
I was testing the model and I went from having acres on straight cash rent to putting them on variable rent with a 10% min max cap.   That all worked fine.   But then I went back to the model and reverted the acres back to straight cash rent.   The model did not revert to straight cash rent but rather continued to make the revenue based rent adjustments.    It seemed to "stick" in variable cash rent mode and would not go back to straight cash rent.

**Comment by KelleyDrake** [comment]
A little more on this issue.   If you go to my Madison County Farm and originally set 1,500 rental acres to straight cash rent, you appropriately get no adjustments to cash rent.   I have the model running on 3/10/2023.   Prices have already come down by that date from the Discovered Projected Price so when I switch to variable cash rent at a 10% min/max I appropriately get reductions in land rent.   For example, when change the model to run those 1,500 rental acres at variable rent with a 10% cap, the rental $ costs in total drop.  -$17k in aggregate made up of -$11k for corn, -$3k for FS beans, and -$4k for Wheat.  That looks correct to me. Using corn as an example, the Spring Projected Discovered price is $5.91 for corn vs the then current harvest futures price of $5.58 as of 3/30/23 or about 5.6% lower.   Rent for corn acres is adjusted lower for corn by that same percentage.  So that appears all to be working. 

But then when I go back to the Farm Specific Data input screen and change the 1,500 variable rent acres back to 1,500 straight cash rent acres (and I simply leave the 10% cap/floor as is...as that should not have any effect in a straight cash rent scenario), I go back over the check the rent in the Detailed Budget and weirdly the adjustment to cash rent is still there -- but the adjustments are all different from before.  For some reason the wheat adjustment is zero but the corn and beans adjustments are the same at -$11k corn, -$3k fs beans and $0 for wheat for a total of -13k.     Setting the acres back to straight cash rent should eliminate all adjustments happening to land rent costs.   It appears to only be eliminating the adjustment for Wheat and leavint the Corn and Beans adjustments as if they were still on variable rent.  Now if I go back and reset the rent cap/floor to 0% from 10%, while leaving the input to straight cash rent, it causes all the rent adjustments to go away and show zero again.    So something strange is happening in the code.   Hope this makes sense.

**Comment by ddrake** [comment]
Should be fixed in commit 41bef17

**Comment by KelleyDrake** [comment]
I tested it and it looks good.  Thanks
