### ISSUE TITLE
Like the Red and Green on Sensitivities but can we Keep the Boxes and Bolds on the 100%/100% and the 90% matrix.

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#123]
I like the color coding of positive and negative numbers in the sensitivities.   Very nice.   I wonder if it would be possible to retain the old boxes and bolds also.   Namely the 100% 100% box and bold is an important reference point for the viewer as it will tie back to the detailed budget whole farm cash flows.   I also liked it when we had the box around the nearby relevant range of 90% to 110% on price and yield.   Would it be possible to keep the red and green colors while also adding back those boxes and bolds?

**Comment by ddrake** [comment]
Yes, I’m sure I’ll be able to do that.  I don’t have internet access here except through my phone so I’m not sure how soon I’ll be able to push the update.  I’ll try using a hot spot from my phone.

**Comment by ddrake** [comment]
This should be fixed in commit #e230485

**Comment by KelleyDrake** [comment]
Testee and it looks great.  Thanks!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 8/6/23 5:14 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Like the Red and Green on Sensitivities but can we Keep the Boxes and Bolds on the 100%/100% and the 90% matrix. (Issue #123)


This should be fixed in commit #e230485
