### ISSUE TITLE
Non-urgent grain marketing feature request

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#127]
As I was working through the tutorial video and got to the grain marketing section, I found that if I wanted to add contracts to existing one, I had to go off line and with paper and calculator calculate the new total contracts and the new weighted average price.   I'm wondering if on the grain marketing input page we could put a simple form tabular format to hold past grain marketing data.   And then, when we add additional contracts, it automatically calculates the new totals and weighted average prices - and then pushes just those totals to the main grain marketing page.   In its simplest form we could have an input table in which we had some information about the contracts.   With two sections, one section for futures, and one section for basis.   Keeping the form simple, we could have columns for Contract Date, Terminal, Bushels, Price/bushel.   I don't think we want to get into delivery month here as that might tend to complicate things.   Suggest that the grain marketing page would appear just as it does today.   And it would bring forward only the total bushels and weighted average prices from the line by line input page.   I think on the line by line input page, in addition to having a place for the inputs, we might also want to show the total expected production, the remaining unmarketed bushels and the current harvest futures market prices.   That way when we add contracted bushels we would have current prices at the ready to use if we wanted, and we'd have immediate context as to the bushels we are selling relative to total expected production and the expected grain that we have left to sell.     This would allow the farmer to not have to go offline to create the weighted averages and they'd also see their own history of futures and basis contracting on the drill down input page.   Just a thought for a potential enhancement and not urgent at all.    What prompted this is that when I am doing the tutorial to add contracts on top of existing contracts, I have to go off to the side and calculate my new totals and weighted average prices.   This new proposed feature would eliminate that step for the user, help avoid errors and the user would be able to see the underlying numbers which are driving the calculations.   Not urgent at all - feature request for down the line.

**Comment by ddrake** [comment]
- So would we key off contract date for time travel?  Excluding future contracts from the weighted averages?
- Would users *have* to input these tables?  Or would we still allow a the two single entries for weighted average in case they prefer to manage them offline in a spreadsheet or farm software system?
- I’m assuming that if they did input the contracts they would want an associated printed report listing the contracts and showing the weighted averages.
- What problems do you foresee with letting them put in a delivery date?  Could it be optional?  I would think they might ask for a report sorted by delivery date.

**Comment by KelleyDrake** [comment]
Good questions.  Again none of this is urgent at all and we should discuss when you get back.

I had not thought about time travel but agree that if they travel back in time prior to the point they entered the contract then those contracts would not appear.

Let's talk about #2.   I could go either way...although I think because of time travel issues, we might be better off requiring them to put in all of their contracts and contract dates.

Probably yes on #3 on printed reports

The problem with delivery date would be that we'd be showing them harvest prices (initially for example Dec for corn and then on expiration, July) in the screen while they could be contracting in a different month at a different price-- say January futures for example.   Probably not a huge problem but trying to think ahead as to confusion that could arise.    I do think this additional feature could be attractive to the farmer and terminals.   If the farmer turned over marketing to a single terminal then the daily contracts could all be linked and then aggregated on the farmer screen and pushed through our model.   Let's talk more about this when you get back.  Longer term possible enhancement.






Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 8/7/23 4:33 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Non-urgent grain marketing feature request (Issue #127)


- So would we key off contract date for time travel? Excluding future contracts from the weighted averages?
- Would users *have* to input these tables? Or would we still allow a the two single entries for weighted average in case they prefer to manage them offline in a spreadsheet or farm software system?
- I’m assuming that if they did input the contracts they would want an associated printed report listing the contracts and showing the weighted averages.
- What problems do you foresee with letting them put in a delivery date? Could it be optional? I would think they might ask for a report sorted by delivery date.

**Comment by ddrake** [comment]
I think this is basically done now as of commit 2a974d3.  I added a CSV download as well as a PDF report.  Any issues or tweaks needed can be added to a new issue -- or discussed over the phone.
