### ISSUE TITLE
Non-urgent feature request relating to ARC-CO and use of SCO

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#128]
If we have title for a crop set to ARC-CO and then select SCO for crop insurance, we get the error message.  That is fine.  But then the user is kind of stuck.   There is not an easy or intuitive way to get out of that screen to go over to the title input page.   The user has to hit the back key twice to get out of the screen and go over the dashboard, change the title to PLC and then come back to pick SCO.   It's a little clunky.   Wondering if when we get to that error message we could provide an option for the user to "click here to change your title selection" taking the user directly to the title input page?   Right now the error message warns the user -- and that is good.   But it is not exactly intutive on how the usere is supposed to get back to the title screen to change title to PLC.   You might want to try this out on a sample farm to see what I'm talking about.   Just turn one crop's acres in title to ARC-CO and then try to select SCO for that crop for crop insurance.   You'll run into the problem and see that it's not super user friendly to get back from the error message and back out to the title screen.    Again a non-urgent feature request.   Not an immediate problem at all.

**Comment by KelleyDrake** [comment]
This suggestion comes from working through my tutorial and running into the non-intuitive input flow.

**Comment by ddrake** [comment]
The addition of the Dashboard link to the top navigation helped somewhat, but I think we should add the dropdown functionality as discussed previously.  It should be simple to implement, not distracting and make it easier for the user to move between e.g. the crop insurance detail view and the title detail view.  [This example](https://play.tailwindcss.com/Tlqyn2rByT) can be adapted.

**Comment by ddrake** [comment]
I think [this](https://play.tailwindcss.com/M2xGxCaBrK) is getting pretty close.

**Comment by ddrake** [comment]
I think [this](https://play.tailwindcss.com/M2xGxCaBrK) is getting pretty close.

**Comment by ddrake** [comment]
I think with the drop-down dashboard links, navigating from the title edit form to the corresponding crop insurance form can be done in two clicks, so I’m closing this for now.
