### ISSUE TITLE
Consider Rolling to Nearby Futures on Expiration instead of July

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#129]
For un-marketed grain we currently use the harvest futures to compute the revenue from the crop (plus assumed basis).   When those harvest futures expire, we roll forward to the following year's July futures.   Since July futures are now considerably higher than the harvest futures for Corn and Soybeans reflecting the carrying costs of storage and interest expense to carry that grain to July, if we stay with what we are doing today, there will be a big jump in revenue and profitability on the data of the November bean and December corn futures expirations.    In reality if the farmer were to sell grain for July delivery, the farmer would have to bear the costs of carrying that grain and those costs would need to be added to the P&L.   I don't think we want to go that route as it would be too complex and confusing.   Instead, another easier fix would be to roll to the next nearby futures upon expiration of the futures.   I think we should do that to avoid the rather misleading "big jump" in revenue and profitability that will otherwise happen if we leave things the way they are.

**Comment by ddrake** [comment]
This should be complete in commit bfa2721.  Closing for now, but will reopen if any issues surface.
