### ISSUE TITLE
Minor title change: Other Non-Grain Income should read Other Non-Grain Revenue

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#130]
On the Farm Specific Data page there are inputs for Non-Grain Income and Non-Grain Expense.    In accounting terms Revenue minus expense equals Income.    What we are calling "Non-Grain Income" is actually "Non-Grain Revenue".     For example in my farm I assume $50k Non-Grain Revenue, $40k Non-Grain Expense.  That will produce $10k of Non-Grain Income in the budget.

**Comment by ddrake** [comment]
Fixed in commit dac9e9e
