### ISSUE TITLE
Suggest in Sensitivity Tables we Retitle "Revenue" to "Revenue (before any title and indemnity payments)"

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#131]
Here is my rationale:    Right now in Sensitivity analysis, "Revenue" correctly and intentionally equals Crop Revenue PLUS Other revenue MINUS Indemnity and Title Payments.   

Recall that Other revenue includes the sum of other revenue associated with a crop (eg straw sales) and revenue from non-crop specific sources (eg. side businesses).    What we are doing today (and I like this approach) is lumping Crop Revenue and Other Revenue together for the sensitivity -- but deliberately excluding Title Payments and Indemnity Payments from the Revenue Calculation. 

Our current title "Revenue" in sensitivity however might be misleading to a viewer who might well think that it includes Title payments and Indemnity Payments.   While I don't love cluttering up the title, I think to make this clearer to the reader, we should change the title in the sensitivities drop down menu to read "Revenue (before any title and indemnity payments)"   Suggest no changes to any calculations -- only a change in the wording of the title for this line item.

**Comment by ddrake** [comment]
Fixed in commit 8df2ca2
