### ISSUE TITLE
Super minor change, $ signs to be added to Total Direct Costs line in budget

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#134]
In Pre-Tax cash flow budget, 14 lined down you'll see the line titled Total Direct costs.   To follow the format of the rest of the table, the numbers appearing in that line item should have a $ in front.

**Comment by ddrake** [comment]
Fixed in commit 9d81657.  Unfortunately, as with the earlier updates, you'll have to update baseline if you want to see the corrections in the baseline budget.

**Comment by KelleyDrake** [comment]
Got it.  No problem at all!
