### ISSUE TITLE
Futures rollforward to nearby months appears to work but wrong product/exchange for Madison County Farm

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#138]
The rollforward to December from September for wheat upon expiration is working.   However for Madison County Farm it is using the Kansas City Hard Red winter wheat contract instead of the CBOT soft red winter wheat contract.   I have not checked other states to see what is happening.   But we should be sure that the correct product/exchange is being used.

**Comment by ddrake** [comment]
Good catch!  It should be fixed now.  I had forgotten that there could be multiple tickers for a market crop type / contract month.  Please re-test!  Thanks!

**Comment by ddrake** [comment]
Fixed in the database view.
