### ISSUE TITLE
Really Like the New Grain Marketing - A Couple of Formatting Comments

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#141]
Grain marketing pages are well done and pretty easy to use and understand.   A couple of suggestions:   On the printout of the contracts, I think we should provide the farmer a bit more information.   Suggest we add a row for each crop (futures and basis) with total bushels sold.   And under price we provide a weighted average price of what has been sold.  

Also think we might want to add, just below those new totals, the total estimated production bushels, % sold and then the remaining bushels to be sold.   So on the printed report, the farmer will immediately know how far along on marketing he/she is.   

Also, a minor additional point but in my Demo model I have no wheat acres planted but wheat is showing upon on the grain marketing report.   If possible, would suggest that if we have no acres, we don't show that crop on the report.

**Comment by ddrake** [comment]
This should all be in place now per commit a79672a.
