### ISSUE TITLE
Add basis dimension to revenue and cash flow sensitivity tables.

### ISSUE THREAD

**Issue by ddrake** [ddrake/Integrated_Farm_Budget_Tool#149]
From @KelleyDrake:
Our model kind of assumes that average basis in a year is pretty steady.  Basis has absolutely collapsed of late.  For Mississippi terminals harvest basis has fallen from +.10 to -.70 in just a few weeks. I think same is true across the country.     This shows that basis can change fast and far to both upside and downside.    Exposing the farmer to that basis risk. And making me aware that this assumption of a fixed relatively stable basis for uncontracted is probably not realistic and an additional risk vector that we might want to take into account.  

 I wonder (and this is just brainstorming) if we might also be able to sensitized basis. And create a three- way matrix (instead of two way) for  sensitivities.  An x, y z axis matrix 

And for visualization of sensitivity tables you might have a bar that you could drag from say left to right.  Middle would be 100% of assumed basis for uncontracted.   Then you could slide the bar to the left or right off of centerpoint to adjust basis down or up (probably by cents per bushel instead of %) and it would "animate" the sensitivity tables.  You'd only see one x,y two way matrix on the screen at any moment, but like an animation, you could slide the bar and the sensitivity image would change like a frame in a movie.   So as you slide the bar to the left the sensitivity tables would go more negative if basis is not all contracted and if you slide to the right it would bump up basis for all the uncontracted.  This would have no bearing on costs, indemnity or title sensitivities.  It would only impact revenue and cash flow sensitivities. 

 So imagine instead of one sensitivity matrix for a given view (whole farm profit for example), instead the model would produce say 11 total views.   You'd only show one at a time.   But as you slide the bar to the left, you'd see the sensitivity at lower uncontracted basis assumed.  And if you slide the bar to the right you'd see the impact of the higher basis flowing through the model.   Almost like one of those kids books that had the animated cartoons when you flipped the pages.  You could scroll left to right and "animate" the results for basis changes.   

 So for example in my Madison County model I think I have uncontracted basis set at 20c for corn and beans and 5c on wheat.   Maybe we could do a base case run and then 5 runs on downside and 5 runs on upside.   Where basis would drop or increase incrementally by 10c for each of corn, wheat and beans.  So we'd be running for corn and beans, if 20c positive was base case a range of:

-.30, -.20 -.10, 0, +.10, +.20, +.30, +.40,+.50 +.60, +.70

For wheat if base case was 5c 
-.45,--.35, -.25, -.15, -.05, +.05, +.15, +.25, +.35, +.45, +.55

Perhaps we set the base case increment at 10c but make that a user defined number to allow the user to widen or narrow the basis ranges?   

The first screen that comes up for each sensitivity tab would have the center base case (exactly as it is today).   But with a sliding bar, right or left, the user could see an animation of downside and upside relating to uncontracted basis.    

I know this would create a lot of additional computations that might bog down the model.   I also have no idea how to implement the concept of the sliding bar/animation  that would animate the sensitivities.  

Just a concept.  An idea to bounce around!!  If you think it could be interesting or useful we can add this to the enhancements list.  I think this would be a cool addition for the user and show that locking (or not locking) basis can have serious implications on profit risk.  LMK what you think!!

**Comment by ddrake** [comment]
This would only affect the tables for revenue and cash flow.  

An important question is: @KelleyDrake: Do we need these tables only at the farm level or for all 6 "crops" i.e. (farm, corn, fs beans, wheat, wheat/dc)?  If only at the farm level, that would add 20 tables to the current 30 tables, which would probably not affect render and download time much.  If we need this for all 6 "crops", then for 11 settings we would need to render 12*(11-1)=120 new tables (in addition to the 30 tables we currently render).  It's hard to estimate the performance in this case.

We could try it with your suggested 11 values.  If the performance is bad, we could reduce the number of values to get a reasonable trade-off.

I think a slider is a reasonable choice for the input.  We can modify [this example](https://www.w3schools.com/howto/howto_js_rangeslider.asp).  It will only be used in Javascript so it doesn't have to be a Django form widget.

It wouldn't make sense to add a 'basis sensitivity factor' to market crop because the user could get the same information just by changing the 'assumed basis for remaining'.

**Comment by ddrake** [comment]
I forgot about the diffs.  The table counts should be doubled

**Comment by KelleyDrake** [comment]
Maybe we start with only whole farm revenues and cash flows and see how performance is with the 11 views.   And if performance is bad we then reduce views as necessary.   If performance is still very good then perhaps we add them to all crops.   If not we stop there?

**Comment by KelleyDrake** [comment]
Perhaps we have a switch on the page to turn in basis sensitivity.   "See basis sensitivity"   and when you click on that it adds the views and the extra slider/animation pops up?  That way it doesn't have to be doing them all the time?   I'd need to think what different would be doing?  Is that diffs against the prior model run for each of the 11 screens.   Eg if we changed crop insurance, is the diff screen #11 vs prior screen #11?   If we had a "see basis sensitivity box" I don't think we need all 11 different cases.  And only need the diff on the prior central base case.     If we treat the 'see basis sensitivty" as an add on, then maybe we don't slow standard performance.   As I envision it I like the 11 views and would like them for revenue and cash flow for whole farm and each of the "crops".   But we don't need diffs for all 11 screens and we don't need it running every single time we do a sensitivity.   Could it be almost a one time additional button "run basis sensitivity" to render those 11 sensitivity screens  for 6 crops with no diffs.   Where diffs would onky apply to base case center point basis assumption?  So almost have it be an additional one time calculation that happened only when somebody hit the "run" button and it pops up.  And when they leave the screen and make other changes to the model, and the returned to sensitivities they would see onky what we see today.  And would have to hit the run basis sensitivities to see the 11 screens x 6 crops screens.   And on that run title sensitivities we'd add some sort of header or identifier to show the basis assumed for each screen.   Sceeen #1 would be very low basis and screen #11 very high basis.   We"d show the user somehow what was being assumed at each spot on the sliding bar. And they could print any given screen.   But as soon as they left that basis sensitivity screen, they would have to run a new basis sensitivity to see those recalculated 11 screens all with no Diffs?  Just a thought on trying to not boil the ocean every single time we run sensitivity.   But rather give the user a one time set of animated views on command and lasting only for that one moment in time.   Does something like that makes sense?   Don't have ot all visualized in my mind yet.  But perhaps something like that could be possible?

**Comment by KelleyDrake** [comment]
Thinking of this as almost a drop down option off and underneath the sensitivity tab.   So all core functionality we have right now stays the same.   But from within the sensitivity screen there is an additional option to produce the 11x6 views.  But when they return to the main sensitivities page, those 11x 6 views go away and have to be recalculated to see them again.   We don't have diffs on these. And wr need a little more titles to tell them what basis is neong used and we have the sliding bar only on this screen.    We provide this option only on each of the 6 revenue screens and each of the 6 cash flow screens.   All inside sensitivity such that the main menu doesn't change.    Might something like that work?    Minimizes all the renderings and gets the user to the answer if they drill down to it.    So if I am in wheat cash flow sensitivity screen, I have an option to push a button to see the 11 rendered wheat cash flows basis sensitivities.  When I go back, I am back at the standard wheat cash flow sensitivities screen.   And to ever see that wheat basis 11 screen sensitivity I have to rerun it.  And have that same drop down/additional views functionality as option appearing only on each of the revenue and cash flow screens for each of whole farm and for each "crop" .   And you leave it, those rendering and animation feature go away and you hit run to create that additional animated view.   Jist brainstorming  Thoughts?

**Comment by ddrake** [comment]
> Perhaps we have a switch on the page to turn in basis sensitivity.   "See basis sensitivity"   and when you click on that it adds the views and the extra slider/animation pops up?  That way it doesn't have to be doing them all the time? 

It wouldn't be easy at all to switch this on the sensitivity page, because the way it's implemented when the user clicks the "Sensitivity Tables" link, we generate all the tables we need and selectively hide and show via javascript.  But what could work much better, I think, would be to turn it off via the basis increment you mentioned in the original comment:

> Perhaps we set the base case increment at 10c but make that a user defined number to allow the user to widen or narrow the basis ranges?

For example, we could make it so that if the user sets the increment to 0, we don't compute any basis tables.  I think that basis increment would be set in the market crop edit form under 'Price Sensitivity Factor'.

> Is that diffs against the prior model run for each of the 11 screens.   Eg if we changed crop insurance, is the diff screen [#11](https://github.com/ddrake/Integrated_Farm_Budget_Tool/pull/11) vs prior screen [#11](https://github.com/ddrake/Integrated_Farm_Budget_Tool/pull/11)?

Yes, that's what I had in mind.  The way it's implemented now, every table we show has a corresponding diff table assuming that 1) sensitivity has previously been computed and 2) that the diffs can be computed for all the tables. I.e all tables have diffs or none do.  If a user changes the basis increment, I think that should invalidate the diffs so that diffs wouldn't be available the next time they click on 'Sensitivity Tables'.

**Comment by KelleyDrake** [comment]
Why are you up so early?!   Perhaps we should talk for a bit to conceptualize and discuss implementation possibilities and challenges?   Maybe at 10 central, 8 your time?  Or anytime between 10-12 my time, 8-10 yours?

**Comment by ddrake** [comment]
> Maybe we start with only whole farm revenues and cash flows and see how performance is with the 11 views.   And if performance is bad we then reduce views as necessary.   If performance is still very good then perhaps we add them to all crops.   If not we stop there?

This seems reasonable.

> Perhaps we should talk for a bit to conceptualize and discuss implementation possibilities and challenges?   Maybe at 10 central, 8 your time? 

Sure, that sounds good.

**Comment by KelleyDrake** [comment]
Ok.  I will call you at 10am my time 8am your time.  Look forward to the call!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/1/23 8:57 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Mention ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Add basis dimension to revenue and cash flow sensitivity tables. (Issue #149)


Maybe we start with only whole farm revenues and cash flows and see how performance is with the 11 views. And if performance is bad we then reduce views as necessary. If performance is still very good then perhaps we add them to all crops. If not we stop there?

This seems reasonable.

Perhaps we should talk for a bit to conceptualize and discuss implementation possibilities and challenges? Maybe at 10 central, 8 your time?

Sure, that sounds good.

**Comment by ddrake** [comment]
I think that the range of basis values probably depends on the crop year and the region, but not much on the crop.  I'm thinking that we set the basis increment on the farm year detail form, and use that increment for all market crops.  If we set it to zero, only the standard tables are generated.

**Comment by ddrake** [comment]
Status update: I finished implementing this in the model, and designed a sort of button bar for selecting basis offsets.

 It remains to develop the Javascript in the template to hide/show the button bar, add/remove classes to distinguish the currently selected offset from the others and select the table corresponding to the control settings.

 With 11 offsets, the text data before rendering is 1.5 Mb (quite large).  The rendered data will be considerably larger because of all the HTML tags.  Also, the text data is stored in the database so we don't have to re-compute everything to get PDF reports.  I worry about the database exploding.  I'm designing it to be extremely easy to change the number of offsets in the code (just change one value).  I'm going to start with 3 offset values for testing (e.g. -\$0.10, \$0.00, \$0.10) and see how that goes.

**Comment by KelleyDrake** [comment]
Got it.  Thanks!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/4/23 9:24 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Mention ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Add basis dimension to revenue and cash flow sensitivity tables. (Issue #149)


Status update: I finished implementing this in the model, and designed a sort of button bar for selecting basis offsets.

It remains to develop the Javascript in the template to hide/show the button bar, add/remove classes to distinguish the currently selected offset from the others and select the table corresponding to the control settings.

With 11 offsets, the text data before rendering is 1.5 Mb (quite large). The rendered data will be considerably larger because of all the HTML tags. Also, the text data is stored in the database so we don't have to re-compute everything to get PDF reports. I worry about the database exploding. I'm designing it to be extremely easy to change the number of offsets in the code (just change one value). I'm going to start with 3 offset values for testing (e.g. -$0.10, $0.00, $0.10) and see how that goes.

**Comment by KelleyDrake** [comment]
I agree that we don't need 11 offsets and can do with fewer if it bogs down the model.   Ideally we could get to at least 5.  But 3 offsets with a wide increment could be ok too.

**Comment by ddrake** [comment]
Status update: The UI is in place now.  Diffs and printing don't work yet, but I should be able to get them working soon.

**Comment by KelleyDrake** [comment]
Great.  I will try them out!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/6/23 5:59 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Mention ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Add basis dimension to revenue and cash flow sensitivity tables. (Issue #149)


Status update: The UI is in place now. Diffs and printing don't work yet, but I should be able to get them working soon.

**Comment by KelleyDrake** [comment]
Just took a look.   Looks like it is work in process.   Seeing all the sensitivity screens in sequence.  And not seeing any toggles/buttons for basis sensitivity.   I'll hold off commenting until you have it where you want it.   Thanks!

**Comment by ddrake** [comment]
That's odd.  It's all in place now, including diffs and PDF.  You might need to clear your browser cache if it looks weird...

**Comment by ddrake** [comment]
Ah, I see.  It's working for Madison farm, but it looks like there are javascript errors for some other farms.  I'll get it fixed soon.

**Comment by ddrake** [comment]
I think it's all fixed now.   I set the basis increment to 0.1 for the Madison farm, but it's still 0 for the others.

**Comment by KelleyDrake** [comment]
Ok.  I will check it out tomorrow morning first thing

**Comment by KelleyDrake** [comment]
The new basis sensitivity is EXCELLENT in all respects.   I've tested it out and the computations all look right.   And the presentation to the user is excellent too.    With the 5 choices in the ranges, on my Madison County farm with four crops you can tell the sensitivities are a little bit slower -- but only about 2-3 seconds which is totally acceptable.   I think 5 is right range of total choices -- the buttons are self explanatory and I think look great.    At first, I paused and wondered a little about the placement of the basis increment assumption as the last line under "Report Controls".    I thought it might deserve its own separate line on the form?   But on second thought, it does seem like it is a "Report Control and I think it is fine there.   Suggest you take a quick second look at that placement and see what you think about from a user's perspective.   But if you are OK with it, I am too, and no change suggested.  Overall, I think this is a powerful addition to the model and I will make a new video to show how it works.   Really nice work!

**Comment by ddrake** [comment]
Great— I like It too!  A nice addition.  I do think of basis increment as a kind of report control, especially since setting it to zero turns off the feature.  Complete in commit a5184d6.
