### ISSUE TITLE
Checking on ECO and SCO Indemnity Calculations for FS and DC beans

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#154]
This is another kind of painful one.   Forces us to dig back into the indemnity calculations for FS and DC beans.  The sensitivity analysis indemnity payments don't match what I would expect to see for FS and DC beans.

In my Madison County Farm, I have selected a 75% RP 86% SCO, 90% ECO.   Recall that there is only one benchmark county yield for soybeans (not one for each of FS and DC).   For Madison County for 2023 that benchmark yield is 56b/acre.   The discovered Spring Projected Price is $13.76.   Therefore ECO 90% starts paying out at a revenue trigger of 56 x $13.76 x 90% = $693.5/acre

I am assuming actual yields for FS beans of 64.0/acre and for DC beans of 46.0/acre for both Farm and County.   I have 900 acres of FS beans and 200 acres of DC beans in the Madison County Farm model.   There is only one County Benchmark Yield (not one for each of FS and DC beans).    We won't know the final actual County yield from the RMA for soybeans until June of 2024.   I believe that, in the interim, for purposes of calculating County Actual Yield for the revenue indemnity calculations, that we decided to use the weighted average of FS and DC County yields based on the Farm's split of acres to approximate actual County Actual yield until it is published by the RMA.   So our Actual County Yield for use in the model would equal 60.73 (weighted average of 900 at 64 and 200 at 46). 

  I ran a sensitivity analysis on the model and checked the indemnity numbers that were produced.   In the 100% yield column and at a $10.20 assumed soybean harvest price, I calculated the indemnities that I would have expected to have been paid out for each of FS and DC beans.    Actual County Revenue would equal $10.20 x 60.73 actual yield = $619.4 revenue.   This is $74.1 less than the ECO/SCO guarantee revenue of $693.5/acre.   Therefore, I would have expected for both FS beans and DC beans that there would be an indemnity payment equal to $74.1/acre.   

 And the indemnity dollar amount showing in the FS beans would equal 900 acres x $74.1 = $67k and DC beans would equal 200 acres x $74.1 = $15k.   The numbers that appear in the sensitivity table are close but not exact. 

The sensitivity analysis shows FS bean payment equal to $66k (not $67k) and DC bean payment at $11k (not $15k).   This DC bean payment in the indemnity table of $11k is considerably lower than the $15k payment that I would have expected.   I checked to make sure that the 75% RP policy didn't some how have something to do with the discrepancy.   But there should be no payments under that 75% RP policy. 

As a second test, if I run a lower price of \$8.92/bushel off of the sensitivity table and 100\% yields, I would expect to see \$137k payment for FS and \$30k for  DC for the SCO/ECO coverage and then a small additional payment for DC beans of \$.5k for the RP Policy.   Instead, the sensitivity analysis shows payments of \$102K and \$17k, both considerably lower than my math would suggest.

I will put a simple spreadsheet up on the IFBT website called "Madison County Soybean Indemnity" that shows my calculations.   I also took a screen shot of the indemnity sensitivities for FS and DC beans and pasted those into the spreadsheet.

There is a good chance that I have done something wrong here, and the model is in fact correct.   But I cannot figure it out and was hoping you could take a look and test my logic.  Really sorry to drag you down another rabbit hole here -- but I think I need to reconcile my sidebar calculations with the model to ensure that everything is working properly.

**Comment by KelleyDrake** [comment]
I thought I figured it out -- but it still doesn't match.    Recall that when County benchmark yields are less than Farm approved yields then the farmer pays more for the SCO and ECO insurance but ALSO gets a proportionately higher indemnity payment.   

So for simplicity if Farm Approved yield for corn is 200 and County Benchmark yield is 180, then the indemnity trigger is based on county actual yield vs the county benchmark yield of 180.   But the $/acre shortfall payment is then scaled up to 11.1% higher (200/180).     I thought the same might be working in reverse here.   

Madison County benchmark soybean yield is 56 b/acre.   My Approved yield for FS beans is 55 and my Approved yield for DC beans is 40.   So what I thought was happening is the indemnity payments that I calculated above are being scaled DOWN by 55/56 for FS beans or .982 and 40/56 for DC beans or .714.    For the $10.20 harvest price per bushel example, that ties out the numbers almost exactly.   Scaled down indemnity payments would equal $65k FS and $11k DC beans (vs $66k and $11k in the sensitivity).   So very very close and I thought probably rounding.  

However, if I plug in the $8.92/bushel from the next lower price row in the sensitivity table, my excel model tells me I should be getting $134K for FS and $22K for DC using the scaling factors.  The sensitivity tables, however, are showing me $125k for FS and $17k for DC beans, or considerably below what I would have expected.    

So still struggling with this.   Hope this additional post might help remind us both of the business logic.    Thought I had the answer -- but still seems that I'm not getting the results to match.  I will re-upload the excel file with the base case set to the $8.92 actual harvest prices and including the new scaling factors.

**Comment by ddrake** [comment]
Thanks for digging into this!  Tomorrow I’ll duplicate your Madison farm in my dev database, then start checking against your spreadsheet to find the discrepancy.

**Comment by KelleyDrake** [comment]
This morning I wanted to go back and try to replicate RP SCO/ECO indemnities for a single crop just to be sure that it was working correctly.   I started using a farm with 1,000 acres all planted to corn.   I manually calculated various indemnity scenarios and then matched them to what was showing up in the sensitivity tables.   Everything seemed to be working fine and exactly as I expected.   I then wanted to turn to soybeans and start to figure out the full season and double crop situation.  I deleted my Indemnity Farm which tested corn and then started over creating a new Indemnity Farm to test 1,000 acres of full season soybeans.  That's where I ran into a hitch.     I put in 1,000 acres of rented ground for FS beans (just like I had previously done for corn).   I set all 1,000 acres for FS beans.   I then entered 65 for rate and adjusted yield and 70 in for Farm approved yield.   I then went to look to see what came up for County Benchmark yield.   And weirdly no insurance data would come up on the insurance screen at all.    The crop insurance/crop acreage screen fails to show the standard items that I would need to use to check RP and SCO/ECO indemnities including County Benchmark Yield, Projected Harvest Price, Volatility Factor and Discovered Harvest Price (est).    Not sure if the fact I created and deleted a farm of the same name caused this glitch?   But I had to pause my Soybean testing because these key datapoints did not come up.  Any thoughts on why that might be?   Take a look at my Indemnity Farm on the Crop Acreage/Crop Insurance page and you will see what I mean.

**Comment by ddrake** [comment]
It's a bug.  I get the same issue when I create a new farm year.  I'm working on it now.

**Comment by KelleyDrake** [comment]
Ok. Thanks.   Please disregard my concerns about replicating FS and DC SCO and ECO indemnities.    I have a little bit more confirmation checking to do.   But I now think everything was and is being calculated properly and my concerns were incorrect and unfounded.

**Comment by ddrake** [comment]
Sounds good!  I just finished fixing the issue with the missing RMA data.  I think that bug was introduced last week.

**Comment by KelleyDrake** [comment]
I have finished my testing.   All is good!!   I can replicate everything to do with FS/DC beans and RP and ECO/SCO.   All good!

**Comment by ddrake** [comment]
Excellent -- I'll go ahead and close that issue.
