### ISSUE TITLE
Replicate a Farm Year

### ISSUE THREAD

**Issue by ddrake** [ddrake/Integrated_Farm_Budget_Tool#156]
I added a way for a user to download a script of SQL inserts for one of their farm years by navigating to e.g. https://ifbt.farm/replicate/54 (assuming the user has a farm number 54).  It's not permitted to download a script for another user's farm (unless they happen to be an administrator with impersonation privileges -- i.e. me).  Since the script is pretty useless for anyone who doesn't have direct access to the database (e.g. via pgadmin or psql) so I haven't added the link above to the user interface.  I don't see any security/privacy risk with this current setup.

Two benefits of having this feature are:

1. If a user reports possibly incorrect data generated in their budget or sensitivity tables, I can trouble shoot the issue much more quickly by replicating their farm in my development environment.
2. If a user is having trouble getting set up, and wants to be able to play with a fully functioning farm year right away, I could add a standard demo farm year to their farm years.  For this, it might be simpler just to add a button on the 'farm years' page: "Add Demo Farm".

The main problem with the current script is that you have to perform the insertions pretty much one at a time and replace the placehoders in the script (e.g. farm_year_id?) with the autogenerated key returned after the insertion.  This is error-prone and time-consuming, but does work.  I was able to create an exact replica of Madison farm owned by @KelleyDrake.  

I think there is a way to rewrite the script so that all the insertions can be all at once without copy/pasting generated keys but after quite a bit of searching  and experimentation, I haven't found a solution.  I [posted](https://www.postgresql.org/message-id/CACM7_5Zjm%3DhdPv9F%2B74bwocgABTLi_sFDeVgG2H0HFPYD3LR4w%40mail.gmail.com) to the postgresql mail list today.  Maybe I'll get some help there...

**Comment by ddrake** [comment]
I got several insightful replies to my post within a few hours, one of which was exactly the pattern I was looking for.  The PostgreSQL community is awesome!

**Comment by KelleyDrake** [comment]
Excellent



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/5/23 11:20 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Mention ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Replicate a Farm Year (Issue #156)


I got several insightful replies to my post within a few hours, one of which was exactly the pattern I was looking for. The PostgreSQL community is awesome!

**Comment by ddrake** [comment]
Complete in 8c8278b.  It took 10 hours (lots of deugging), but I learned some useful PostgreSQL syntax and techniques, and I can replicate a farm year exactly in one step now.
