### ISSUE TITLE
Sensitivity Tables Not Appearing

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#158]
I suspect you are working on the basis sensitivity screens.   But FYI when I go to my models and bring up sensitivity, it "flashes" quickly on the screen and then disappears.   Again, I suspect that my be part of your process of getting the basis sensitivity enhancement up and running.  But thought I'd make you aware.

**Comment by ddrake** [comment]
I made a mistake, and accidentally pushed some work in progress on sensitivity to the server yesterday.   As a work-around, I just set the basis increment for sensitivity to zero for all of your farms so your sensitivity tables should work again.

I'll be working on the UI component today.  Once that's in place you'll be able to set the basis increment however you like.

**Comment by KelleyDrake** [comment]
OK   Great.   Thanks!

**Comment by ddrake** [comment]
All in place now
