### ISSUE TITLE
Any Way to Share a Farm With Someone?

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#171]
If I reach out to U of I, for example, I think it would help if they didn't have to set up a farm -- but rather could import or access one of my farms.   My Demo Farm would be perfect for them.    If I could somehow get them that Demo as a starting point, I think it would help with their analysis and appreciation for the tool.   I think that you may have done this already but as I reach out to U of I, is there some way I can point them to a generic farm that is relevant to their specific region?  (like Demo Farm)?

**Comment by ddrake** [comment]
I think we worked this out over the phone...
