### ISSUE TITLE
Edits to the language above the link to the Sources and request for inclusion of publication date if possible

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#172]
This is an edited version (below) of the language that you put in.   I made a few cleanups and added a few sentences.   I don't know how to do a compare write to show you a blackline of the proposed changes.   But i think they are useful and straightforward.

Also, is there any way that you could add the date of publication to the table below?   I know the format of the page is getting pretty tight.   Perhaps a smaller font would allow that?

The "Yield and Expense Budgets" available for selection at the bottom of the "Crop Acreage/Crop Insurance" page are derived from publicly available budgets published by a number of universities in the U.S.  We're grateful to the faculty and staff of these universities for their efforts in assembling budgets from contributors in their states, and hope that the inclusion of these benchmark yield and expense budgets in this application provides a useful budgeting starting point for our users.

In most cases, in order to display a standard set of cost items, it's necessary to re-categorize some of the cost items of the original university budget.  Certain items including market prices, assumed basis and crop insurance premiums are removed from the university budgets and replaced based upon user selections and current harvest prices.   In certain instances, university budgets are incomplete (such as lacking land rent).  In these cases, we incorporate reasonable USDA based data.   Also, note that the budget data used in 'Yield and Expense Budgets' is derived from winter/spring university publications and not necessarily derived from the latest university budget released for the crop year. 

Listed below are all the budget sources for the current year. The highlighted entry corresponds to the crop for which you clicked "Budget Source".

**Comment by ddrake** [comment]
Complete in commit: 83c1a8c.  If it looks funny at all -- e.g. authors not wrapping, etc, you probably need to clear your cache again.
