### ISSUE TITLE
Super minor format change to PDFs of printed detailed budgets

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#173]
When you go to print the detailed budgets (baseline, current and variance), on the first page where revenues are calculated the underlines for totals are off in four places.   For example, there is an underline 6 lines down (underneath the things being totaled), when it should be at 5 lines down.   Wherever there are totals (4 places on the PDF) the underline should be on the line immediately above the totals.   Note that everything appears fine on the screen.   It is only on the PDF where the total lines get shifted.  Also on the second page of the budget detail PDF, everything looks fine.   It is only a problem on the PDF on the first page where the Crop Revenue is being calculated.    Hope that makes sense.

**Comment by ddrake** [comment]
Complete in commit: 62d4a38
