### ISSUE TITLE
Discovered Harvest Prices Look to Not be Updating Properly

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#185]
The IFBT tool has estimated discovery price equal to $4.91 for corn today.   The RMA has $4.92.  For beans the RMA has $12.83 and IFBT has $12.81   So not sure if things are updating properly.

**Comment by ddrake** [comment]
Fixed in commit: 1ae83da

**Comment by ddrake** [comment]
Correction: the commit was [7df54e1](https://github.com/ddrake/scripts_ifbt/commit/7df54e1b022df6fd43754df539f1f97612ad6235)

**Comment by KelleyDrake** [comment]
Great.  Thanks.   I just tested and it looks good now.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 10/21/23 10:24 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Discovered Harvest Prices Look to Not be Updating Properly (Issue #185)


Correction: the commit was 7df54e1<https://github.com/ddrake/scripts_ifbt/commit/7df54e1b022df6fd43754df539f1f97612ad6235>
