### ISSUE TITLE
Something Glitching on Presentation of Insurance Data

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#189]
I went to my Demo Farm to see if Discovered Harvest Price had been updated and finalized.   If you go to the Crop Acerage/Crop Insurance screen, you'll see that discovered Projected price shows $4.88 (that should be $5.91), Volatility Factor shows 221.9 (which I believe is benchmark yield for crop insurance), and Discovered Harvest price shows .18 (the 2023 Volatility Factor for corn).   So something funky going on.   Might have to do with your updating based on what we discussed today?   Please take a look and you'll see what I'm saying.

**Comment by ddrake** [comment]
Just fixed it.
________________________________
From: KelleyDrake ***@***.***>
Sent: Wednesday, November 1, 2023 5:44 PM
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ddrake/Integrated_Farm_Budget_Tool] Something Glitching on Presentation of Insurance Data (Issue #189)


I went to my Demo Farm to see if Discovered Harvest Price had been updated and finalized. If you go to the Crop Acerage/Crop Insurance screen, you'll see that discovered Projected price shows $4.88 (that should be $5.91), Volatility Factor shows 221.9 (which I believe is benchmark yield for crop insurance), and Discovered Harvest price shows .18 (the 2023 Volatility Factor for corn). So something funky going on. Might have to do with your updating based on what we discussed today? Please take a look and you'll see what I'm saying.

**Comment by KelleyDrake** [comment]
Cool.   That was quick!

**Comment by ddrake** [comment]
I was working on it while you were creating the issue report...
________________________________

**Comment by KelleyDrake** [comment]
We’re efficient!

**Comment by ddrake** [comment]
Fixed in scripts_ifbt commit: [f4e5e3c](https://github.com/ddrake/scripts_ifbt/commit/f4e5e3c)
