### ISSUE TITLE
Grandview Farm 500 Error on Sensitivity Tables

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#194]
I just added a Grandview Farm model.  When I went to sensitivities I got a 500 Error.

**Comment by ddrake** [comment]
Fixed in commit 2254008.  It took a while because the replication code had bugs and hadn't been updated with some recent model changes so I had to get that working first.

**Comment by KelleyDrake** [comment]
Thanks Dow!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 11/6/23 5:36 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Grandview Farm 500 Error on Sensitivity Tables (Issue #194)


Closed #194<https://github.com/ddrake/Integrated_Farm_Budget_Tool/issues/194> as completed.
