### ISSUE TITLE
Approved Yield Not Appearing on the Form

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#197]
I am building a central Iowa farm to gather data for a blog post.   I added rate yield, adjusted yield and approved yield to the input form.  However when I go back to the saved form, Approved Yield does not appear.

**Comment by ddrake** [comment]
Thanks for letting me know!  A few days ago, I renamed that variable from 'ta_aph_yield' to 'appr_yield', but I didn't do a thorough search and replace.  It should be fixed in commit 8e6dff9
