### ISSUE TITLE
Are Title Payments Computing Correctly?

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#201]
In my Demo farm I have corn, bean and wheat title acres all elected in ARC-CO.   I have farm and county yields locked as final at 222 for corn, 69 for beans and 85 for wheat.   When I run the title sensitivity table it produces no payments even under very low MYA price scenarios.   ARC-CO benchmark revenue is $886/acre for corn, $668/acre for beans and $434/acre for wheat.  At the 50% price sensitivity factor, MYA for corn is being calculated to equal $3.52, beans at $9.35 and wheat at $6.12.   That would make county revenue at that 50% price factor equal to $781/a for corn, $645/a for beans and $520/a for wheat.   Therefore, I would expect payments to trigger for corn, and beans and not wheat.   But I am not seeing any payments being made.   I may be missing something or screwing something up on my end?     Can you take a look?

**Comment by ddrake** [comment]
I replicated the demo farm and set the price factors to 50%.  That gave me MYA prices of \$3.52 for corn, \$9.35 for beans and \$7.20 for wheat.  So the same as you reported except higher for wheat, which shouldn't matter in this case.

Did you forget to multiply the benchmark revenue by 0.86? 

I'm seeing arc guaranteed revenue for corn as \$762 and for beans \$575 so the actual revenue is higher thant the guarantee.

**Comment by KelleyDrake** [comment]
Yes. I forgot the 86%  thanks!

**Comment by ddrake** [comment]
Sounds good!
