### ISSUE TITLE
Thought for a User option - Offer a Pre-loaded generic budget as example for the user

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#203]
Not sure if this is a good idea or not.   But perhaps when a user signs in the user already has a basic farm year up and running to be able to look at.   This might help them create their own farm.    For example, we could have a central IL farm with corn and beans with reasonable assumptions for insurance selections and yields, budgets etc.   That way the farmer could play with assumptions on that farm concurrent with setting up their own farm.   Basically, providing them with a pre-loaded "base case".   Just a thought to discuss and nothing immediate or urgent.   They'd just see a demo farm and could refer to those assumptions as they input/choose their own?

**Comment by ddrake** [comment]
This is similar to a suggestion I made a while back, of adding a link "Add Demo farm" just below the "Add a farm" link on the Farm Years page.  I think we decided against it at the time because an Illinois farm might be confusing to users in some other states.  We also considered the idea of a set of demo farms covering a range of regions, but that seemed too complicated.

I think adding the link "Add Demo farm" would be better than just automatically adding it upon registration, so the user could decide if they wanted it, and so if they later deleted it, they could recreate it by the same process.

But my feeling is that the tutorial videos and user guide are sufficient to get someone started quickly, and that the Demo farm would be less useful, since it would inevitably include choices that wouldn't make sense to many users and thus generate confusion.  Some users might even mistakenly assume they were supposed to customize the Demo farm, rather than create their own.

**Comment by KelleyDrake** [comment]
OK.  Sounds good. 11ct, 9pt?



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 12/5/23 4:51 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Thought for a User option - Offer a Pre-loaded generic budget as example for the user (Issue #203)


This is similar to a suggestion I made a while back, of adding a link "Add Demo farm" just below the "Add a farm" link on the Farm Years page. I think we decided against it at the time because an Illinois farm might be confusing to users in some other states. We also considered the idea of a set of demo farms covering a range of regions, but that seemed too complicated.

I think adding the link "Add Demo farm" would be better than just automatically adding it upon registration, so the user could decide if they wanted it, and so if they later deleted it, they could recreate it by the same process.

But my feeling is that the tutorial videos and user guide are sufficient to get someone started quickly, and that the Demo farm would be less useful, since it would inevitably include choices that wouldn't make sense to many users and thus generate confusion. Some users might even mistakenly assume they were supposed to customize the Demo farm, rather than create their own.

On another subject, these were the tickers that were missing from the barchart scraping script:
("ZSQ24", "2024-08-14"),
("ZSU24", "2024-09-13"),
("ZSQ25", "2025-08-14"),
("ZCU25", "2025-09-12"),
("ZSU25", "2025-09-12"),
Going forward, the procedure for updating this script for a new crop year will be correct.

I should have time to fix the budgets today too so if you want to meet again tomorrow, that should work. Also, if you have a sequence of updates you want me to run, I can do that and send you the PDF output after each step.

Best,
Dow

________________________________
From: KelleyDrake ***@***.***>
Sent: Tuesday, December 5, 2023 10:42 AM
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ddrake/Integrated_Farm_Budget_Tool] Thought for a User option - Offer a Pre-loaded generic budget as example for the user (Issue #203)


Not sure if this is a good idea or not. But perhaps when a user signs in the user already has a basic farm year up and running to be able to look at. This might help them create their own farm. For example, we could have a central IL farm with corn and beans with reasonable assumptions for insurance selections and yields, budgets etc. That way the farmer could play with assumptions on that farm concurrent with setting up their own farm. Basically, providing them with a pre-loaded "base case". Just a thought to discuss and nothing immediate or urgent. They'd just see a demo farm and could refer to those assumptions as they input/choose their own?

**Comment by ddrake** [comment]
Yes -- that should work fine!
________________________________

**Comment by ddrake** [comment]
For now, I think we decided not to pursue this.

**Comment by KelleyDrake** [comment]
Agreed.   I do have an idea for down the road but we can discuss later.  Idea is once a farmer picks a county we "pre load" what a farm might look like in that county.   Adds a lot of judgement calls and complexity....so not a near term idea.   But perhaps longer term we could do a "smart" pre-population of data.  So a typical farm in a particular county based on likely mix of crops and using farm yields  based on county yields,we pick a standard set of acreage mix for a farm in that county, make sensible title choices and acreage assumptions, pick logical insurance coverage, and pick a local relevant budget.    Not to do anything now.   But if someone could see a farm that potentially looked a lot like theirs, then it might seem less daunting?   Not for now...but when we go full "AI", we should be able to model their whole farm for them!!   Not for now...but to think about for down the road.
