### ISSUE TITLE
Ohio 2024 Farm Server 500 Error

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#210]
A few strange things are happening for my Ohio farm.   Ohio does not yet have budgets out.   So I wanted to check to see if IFBT was pulling the 2024 data that I created by rolling forward the data from 2023 using the global adjustments.   When I go to my spreadsheet and look at Ohio high productivity corn, I see yield of 221.5 and land rent of $285.8/acre.   When I go to IFBT that Ohio High Productivity corn budget title in the drop-down menu has 221 b/acre and $285 cash rent.   I would have thought with rounding, the IFBT title would pull in 222 yield and $286 cash rent.   Not a big deal but I found that a little odd.

I then wanted to dig in further and confirm that the individual cost items in the IFBT detailed budget matched the individual line items in my spreadsheet.   When I hit detailed budget in IFBT I got a server 500 error.   Therefore, I was unable to check to see if the individual cost line items for Ohio High Productivity corn in IFBT did match my Ohio high productivity corn from my spreadsheet.

**Comment by KelleyDrake** [comment]
I fixed the server 500 issue.   I initially had not put in any crop insurance information (no adjusted yield, rate yield, approved yield).  When i added those the server 500 error went away.   I could see that being potentially confusing for a user as I did not get an error message when I went to try to pull down the budget.   I got the server 500 error right away without any message telling me that I needed to add the insurance data.   Just FYI.    I will look at the individual cost items now to confirm they came over correctly.

**Comment by ddrake** [comment]
Thanks – I've seen the report and have been working on troubleshooting.  In general, it helps me a lot if, when you get a 500 error, you don't make any further changes.  That way, I can replicate the farm and diagnose the error.

**Comment by KelleyDrake** [comment]
I think I have an issue with my global adjustments that are being applied to 2023 in my spreadsheet.   I need to spend some time doublechecking things and, when I get things fixed and checked, I will need you to re-upload the data from my spreadsheet.   Sorry about that.   I am tied up today and will be driving to the lake tomorrow.   So I will have the ability to debug my spreadsheet starting tomorrow afternoon and should have everything working by Wednesday.   So please stand by.

**Comment by KelleyDrake** [comment]
Understood.   Here is what I did.   I picked Ohio farm and a county there.   I put in 1,000 acres of rented land.   I then put those 1,000 acres all in corn.   I did not make any selections or inputs on crop insurance.   I then selected the Ohio High Productivity drop down budget.   And that was when I got the server 500 error. 

I then went back in and added rate, adjusted and approved yield -- and then went into budget and did not get the server 500 error.    Not sure if that helps.

**Comment by KelleyDrake** [comment]
I recreated the problem with farm Ohio2 if you want to take a look at that.   I still have a problem with my data that I need to resolve.

**Comment by KelleyDrake** [comment]
To be more specific, I recreated the Server 500 error with a farm called "Ohio2"

**Comment by ddrake** [comment]
Thanks for doing the testing!
The 500 error should be fixed with commit: 6b81497
The rounding issue should be fixed with commit: a4e49b0

I'll leave this open for now

**Comment by KelleyDrake** [comment]
I found a couple of errors in my input form and fixed those.   I also made a few changes to my judgment calls on global adjustments.  I think I have everything sorted out and working now.   But before re-uploading, I'd like to spend some more time double checking.   I'll have that ready by end of the day Wednesday at the latest.

**Comment by ddrake** [comment]
That sounds fine!

**Comment by KelleyDrake** [comment]
I just finished updating and checking my budget data entry form and uploaded it to the IFBT google share drive.  It is called “2024 Budget Entry Form 1.2.24”.

I have not heard back from the FSA on timing of ARC/PLC yet.  As of a moment ago, the 2024 Program data was not up on their website.   I’ll keep you posted if/when I hear back from Henry Queseda from FSA.

I think once we get the FSA data (hopefully soon) and get it loaded, then I think that you and I should do some additional testing for a day or so.  Then, once we feel good about the 2024 IFBT model, then you can commence the e-mail marketing campaign.    If ARC/PLC looks like it will drag on a long time, then we can revisit my suggested timeline.

Sound OK?

**Comment by ddrake** [comment]
Yes, that sounds fine.

**Comment by ddrake** [comment]
I think I have the updated budgets in place correctly now.   Let me know if you see any issues.

**Comment by KelleyDrake** [comment]
Great.  I will do a bunch of testing tomorrow.   Thanks!

**Comment by KelleyDrake** [comment]
I did some checking this morning.   It appears your fix did clear the original issues as expected and yield rounding in budget dropdown is working and the Server 500 error no longer comes up.   I also now have followed the budget data through from my models.  Looking at 2023, checking my adjustments, and then ensuring that the adjusted 2024 data are coming in correctly to IFBT.   Everything looks to be working perfectly.   Thanks!

I will keep building farms and looking for issues and will report on anything that comes up (if anything).   We just need updated 2024 ARC/PLC data to pull through the IFBT model and do some quick checks on that.   I will also watch to see that crop insurance data is coming in as expected.  Some of Texas corn and beans are already in price discovery (Dec 15-Jan 14).   So I will double check that too this morning.  But all looking good!

**Comment by KelleyDrake** [comment]
I had a good call with Mike Hogan from CGB.   He is going to have some people internally and perhaps externally try out the product.   I offered to walk anybody through it at any time.   They have some rudimentary tools internally but like this better.  And will be thinking about this as a complement or alternative to what they have.  So positive…. but like everything will take time to play out.  I low keyed our expectations and timing.

**Comment by ddrake** [comment]
Nice!

Sent from my iPad

On Jan 3, 2024, at 9:18 AM, KelleyDrake ***@***.***> wrote:

﻿

I had a good call with Mike Hogan from CGB. He is going to have some people internally and perhaps externally try out the product. I offered to walk anybody through it at any time. They have some rudimentary tools internally but like this better. And will be thinking about this as a complement or alternative to what they have. So positive…. but like everything will take time to play out. I low keyed our expectations and timing.

**Comment by ddrake** [comment]
This issue is resolved.
