### ISSUE TITLE
Add a static 'About Us' page

### ISSUE THREAD

**Issue by ddrake** [ddrake/Integrated_Farm_Budget_Tool#217]
@KelleyDrake : Please send the photo you want me to use (if you want one).

**Comment by KelleyDrake** [comment]
Here you go.   Hope that works.

**Comment by ddrake** [comment]
How about I'll start a document on the Google drive, and you add your photo and text there?

**Comment by ddrake** [comment]
You should see a document "About Page Content" in the root of the Google drive -- feel free to edit as desired...

**Comment by KelleyDrake** [comment]
Dow,

I am also now out of commission for today and tomorrow but back online Wed.

Best
Kelley

**Comment by ddrake** [comment]
Complete in commit 2745f77
