### ISSUE TITLE
Updating U of I budgets

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#221]
I mentioned in an e-mail yesterday that the January 2024 updated U of I budgets had not come through but that the new budget source data had come through.   Turns out I was incorrect and the new budget data did come through.   I just did not take the right steps to access those and replace the old ones on my IL farms.    I knew I needed to update the budgets to replace them in the drop down in the "crop acreage/crop insurance" inputs screen.   But yesterday when I thought they were not there, what I had done was simply "reclick" on the same budget (Central IL low rotating) thinking that that would update and replace the old budget.   That did not work.   The good news is that this morning, I went into my IL budgets and instead of "reclicking" on the same cental IL low budget, this time I first selected no budget "-----" to clear the budget out.   And then went back down and selected that same budget that I wanted (Central IL low rotating).    This process DID update the budget from August to January.   So you did port over the new budgets from the excel Upload Form to IFBT.   I was just not initially accessing that new data properly.   I'm fine with this process for users but think that if we alert users that there is a new budget available that they should take the steps that I took in "zero out" the old one and then selecting the same budget title to access the new one.   Also, as I mentioned in my e-mail, I did not get an e-mail that a new budget was available (as I think I had expected to receive) alerting me to the fact that there were updated budgets that I could download.   So my immediate problem is fixed.  But I don't think that a user might make the same mistake and just reclick on the budget title that they wanted - but it would not update.  Instead they apparently need to clear it out completely and then click on it again.    Does that all make sense?

**Comment by KelleyDrake** [comment]
I started updating my Illinois farms using the zero out and reselect procedure.  Namely first selecting the no budget "-----" then reselecting the correct IL budget.   I will, however, leave my Madison County Farm non-updated so that if you like, you can try it out for yourself.  Meaning if you go into my non-updated Madison County Farm budget and re-click on central IL low it will not update the budgets.  But if you zero it out by selecting "------" and then reselect central IL low, it works.

**Comment by KelleyDrake** [comment]
FYI The new central IL low rotating budget that I use for Madison County farm has corn seed at $136/acre and the old budget has corn seed at $144/acre.  So when that change from $136 to $144 happens, you know that the new budget has replaced the old one.    Just to be sure, I tried my original incorrect procedure again...namely simply re clicking on central IL low rot and it did not update.   So if you want to see for yourself that "reclicking" does not refresh the budget you can try it out with my Madison County farm.

**Comment by ddrake** [comment]
This should be working the way you want now -- as of commit 4d88f63

**Comment by ddrake** [comment]
The above code change actually broke the entire interface for browsers like chrome and edge that do not support a click event on an option.  

The code was reverted to the original version (using the select change event).  The emails were updated to instruct the user to de-select, then re-select budgets to update them.  Supposedly JQuery supports click events on options so that is another possibility, but for now we don't introduce that dependency.
