### ISSUE TITLE
Trouble Making a Texas Farm,  403 Forbidden error

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#222]
I attempted to build a farm in south texas to check to see if the crop insurance data had updated.   I used Bailey County, TX.   When I went to create it I got a 403 Forbidden error.

**Comment by ddrake** [comment]
Users are currently only allowed 10 farms for a given crop year.  But I'll try to add some validation to that effect.

**Comment by ddrake** [comment]
I added validation in commit b5a51fd.  Let me know if you think the 10 farm limit needs to be increased.

**Comment by KelleyDrake** [comment]
OK  that makes sense.   You can leave it at 10 farms.   I’ll clean up my farms.
