### ISSUE TITLE
IFBT not exactly matching the rolling price discovery data

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#227]
This is not a big deal but might also be solved by the possible enhancement of going directly to the RMA for both volatility and running discovered prices during the discovery period.   As of 2/20 we had an average discovered corn price of $4.69 as compared to RMA of $4.70.   We had an average discovered bean price of $11.64 as compared to RMA of $11.66.    So our average prices are not exactly matching RMAs.    Not a big deal but wanted you to be aware of this minor price discrepancy.   If we were, at some point in the future, to make the previously discussed enhancement relating to pulling down RMA's data directly (instead of calculating the prices and using last year's volatility), we would match them exactly.    FYI IFBT is using .18 volatility (last year's) for corn and RMA's latest calculation is .19.   IFBT's soybean volatility is .13 (last year's) as compared to .15 for RMA.    Nothing urgent to do here.   But if we could ultimately match RMA exactly during discovery periods by "grabbling" their data, we'd not have these minor discrepancies on average prices to date or volatility factors that are resident in IFBT currently.   I'll submit this as a new issue.  But it is really an elaboration on the prior closed issue.

**Comment by ddrake** [comment]
Sounds good, but the prior issue #223 isn't closed.  If it's ok with you, for simplicity, I'll add your recent comment to that issue and close this one.

**Comment by KelleyDrake** [comment]
Yes. Of course.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 2/21/24 6:25 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] IFBT not exactly matching the rolling price discovery data (Issue #227)


Sounds good, but the prior issue #223<https://github.com/ddrake/Integrated_Farm_Budget_Tool/issues/223> isn't closed. If it's ok with you, for simplicity, I'll add your recent comment to that issue and close this one.

**Comment by ddrake** [comment]
Merged with issue #223
