### ISSUE TITLE
Tried to Create and Ellis County Texas Farm and got 500 error

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#238]
Ellis County Texas was one with the missing corn and soy.  Does not appear to be fixed yet fyi.

**Comment by ddrake** [comment]
You may need to delete the farmyear and re-create it.  Then, it should work.  Please let me know...
There were some materialized views that I forgot to run after I updated the insurance_dates table.

**Comment by KelleyDrake** [comment]
Yes.  Rebuilt the farm and it works now.



Sent from my Verizon, Samsung Galaxy smartphone




-------- Original message --------
From: Dow Drake ***@***.***>
Date: 4/11/24 4:48 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Tried to Create and Ellis County Texas Farm and got 500 error (Issue #238)

-------- Original message --------
From: Dow Drake ***@***.***>
Date: 4/11/24 4:48 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Tried to Create and Ellis County Texas Farm and got 500 error (Issue #238)


You may need to delete the farmyear and re-create it. Then, it should work. Please let me know...
There were some materialized views that I forgot to run after I updated the insurance_dates table.
