### ISSUE TITLE
2023 crop years getting server error

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#245]
I went back to look at two 2023 crop years and got server errors for both.  Not sure what might be the cause.   2024 seems to be working fine.

**Comment by ddrake** [comment]
There were two separate bugs in the case when an FSA crop had a final RMA county yield (wheat).  In the context of the sensitivity table, this needs to retur an array sized like the array of yield factors, but a scalar value was being returned.
