### ISSUE TITLE
Not able to back test SCO and ECO payments for 2023 Crop Year

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#254]
The RMA just released final county yields and I wanted to test out IFBT to ensure they came into the model and were being used properly.   I have a 2023 farm called "Demo Farm" which is a Champaign IL farm.   In that farm I had previously selected an 85% RP policy for corn.   I was curious to see if I went back and added SCO and ECO up to 95% for corn whether crop insurance payments would trigger.   I moved my corn title acres out of ARC-Co to PLC (so as not to trigger a problem with SCO).   But then I still get an error message that IFBT needs Planted Acres, Irrigated/Non-Irrigated, Rate and Adjusted Yields.   Those items are all already set in the model - but IFBT seems to be looking for them as if they are not there.    Is it possible to do this type of "back testing" in IFBT to see how an alternative crop insurance policy (like RP 85% SCO 86%/ECO 95%) would have performed?    Or is that prohibited by the model?

**Comment by ddrake** [comment]
You should be able to change those settings since all your premiums (for all choices of policy, level, etc) have been computed and stored in the database.  You can't change the fundamental items needed to compute crop insurance premiums, such as acres, crop type, irrigation status, etc...  I'm looking into this issue now.

**Comment by KelleyDrake** [comment]
Thanks!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/18/24 1:26 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Not able to back test SCO and ECO payments for 2023 Crop Year (Issue #254)


You should be able to change those settings since all your premiums (for all choices of policy, level, etc) have been computed and stored in the database. You can't change the fundamental items needed to compute crop insurance premiums, such as acres, crop type, irrigation status, etc... I'm looking into this issue now.

**Comment by ddrake** [comment]
There was a gap in my understanding of HTML form submission.  I was not aware that setting the disabled attribute on certain form elements can prevent their data from being submitted.  At the time I added the javascript code to handle disabling certain form fields for past years, I had no good way to test that code.

I changed the javascript to remove this attribute from elements when the form is submitted.   I believe this form should be working correctly now.

**Comment by KelleyDrake** [comment]
Thanks!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/18/24 3:12 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Not able to back test SCO and ECO payments for 2023 Crop Year (Issue #254)


There was a gap in my understanding of HTML form submission. I was not aware that setting the disabled attribute on certain form elements can prevent their data from being submitted. At the time I added the javascript code to handle disabling certain form fields for past years, I had no good way to test that code.

I changed the javascript to remove this attribute from elements when the form is submitted. I believe this form should be working correctly now.
