### ISSUE TITLE
Detailed Budget Model Working But Sensitivity Tables are Not

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#48]
In my current model, the detailed budget at the default 100% price factor and 100% yield factor produces a whole farm pre-tax cash flow or $3,064k   This appears to be correct and is very close to my Grandview Benchmarking tool.   Recall that in my current version of the IFBT Marquis Farm model, I input personalized assumptions Grandview for Corn and FS beans, and use U of I central low productivity budget for Wheat and DC Beans.   It looks like my personalized inputs and the inputs from U of I are all coming in and computing correctly in the detailed budget model.   So all good so far.

However, when I go the whole farm sensitivity analysis, at the 100% price factor and 100% yield factor I am seeing the Pre-tax cash flow at $821k and not $3,064.   So something is not working in that sensitivity analysis. This is the main point.

But here are a few other minor suggestions.  In the Detailed Budget Model page, to improve readability, I'd suggest shrinking the font size, putting underlines under titles and under subtotals if possible.  Also, the line item 7 lines from the bottom reads "Land Costs".   That should instead read "Land Rent" (as this is the rental portion of land costs and not the owned portion of land costs which comes in just below).

This maybe should be a separate "new issue", but I used to see the Yield Variablity factor that is used for each crop (which comes over from the university budgets) as an editable input.   I don't see either that Yield Variability default or the ability to edit that anymore.  I think we should try to put that back and make that a variable that can be modified.    

Also recall that when I started building Marquis Farm (Grandview), I first selected IL Central Low Productivity for each of the four crops. 
 I then went in and customized the Corn and FS Beans budgets for Grandview  (Marquis Farm).   I did not customize the Wheat and DC beans crops.  In the Detailed Budget, those costs are appearing correctly.     But when I go back to the "Farm Crops" tab, at the bottom it says "Select Budget" and provides the drop down and shows Alabama (alphabetically the first budget).   So it would appear to a user that somehow Alabama budget is being used, when it is not.   Or that perhaps they need to do a new drop down - which I don't think we want to allow them to do.    So while the model does seem to correctly be using my customized costs for Corn and FS Beans and the UofI low productivity for Wheat and DC beans, this drop down is confusing.       Take a look and I think you will see what I mean.

**Comment by ddrake** [comment]
Will address this once #55, #58, and #61 are complete.

**Comment by ddrake** [comment]
The original comment describes four separate issues/requests.  I've broken it out into those individual issues.  The main issue (incorrect values in sensitivity table) should be fixed now.  There were also a number of issues with the budget values that have also been fixed now.  If a new issue is identified related to _values_ in detailed budget or sensitivity tables, please create a new issue, rather than re-opening this one.
