### ISSUE TITLE
Handling Title Payments When There are No Planted Acres for a Crop

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#49]
I wrote an e-mail to you this morning but I now don't see it in my sent items.   It's about an edge case that I had not previously considered that could cause FSA title payments to go haywire.   I'll rewrite my concern here.   I believe that currently, when a farmer starts to build a budget, he is shown all the crops that are available in his county.  Then if he does not have planted acres to one or more of those crops, then no budget column is computed or shown to the user.   But what happens to Title payments?   For example if a farmer plants 1,250 acres all to corn.   But he has 500 corn title base acres, 500 bean base acres, and 100 wheat base acres.   If/when title payments are triggered and paid, where do these title payments go?   I think even in circumstances where there are no planted acres, we'll still need to keep all the possible crop columns in the detailed budget in order to have a place to put the title payments.  That will clutter up the presentation, but I don't see a way around it.   In this case you'd have bean and wheat columns that are not really relevant as you'd have no planted acres.    But in a sensitivity/circumstance where a title payment for beans or wheat were made, we'd see that revenue line item show up in the detailed budget and everything else would be zero.  

 As a related item, right now I think we calculate bean title payments and then pro-rate those across FS beans planted acres and DC beans planted acres.   That works as long as at least some acres planted to either FS beans, DC beans or both.   But in the case where we have NO planted bean acres, where do we want to put the bean title payments in the detailed budget?   Perhaps in this edge case we just default all the bean tile payments to the FS beans column?    Hope this all makes sense.   We can discuss anytime that is convenient for you.

**Comment by ddrake** [comment]
I may have a fundamental misunderstanding with this that may require a major restructuring of the code.  I’ll review the code when I have a chance.

**Comment by KelleyDrake** [comment]
In your e-mail to me you suggested that if there is only corn planted we put all the title payments to corn, regardless of where they came from.   

That would be a fundamental change from the simplebudget tool   But I suppose we could make that change and change up the logic.  And first calculate corn, wheat and beans total payments subject to the cap.   And then simply allocate those payments to actual planted acres.    So for example, if we planted half corn and half beans and no wheat, and we had no corn or bean title payments but did have a payment for wheat, we'd just split the wheat payment between corn and beans.   

That disconnects the planted crop from the title payments.   I have always kind of considered title payments as a free insurance policy for each crop that triggers when bad things happen to that crop (low prices, low yields).   I know that title payments have nothing to do with planted acres, but my logic of tying title payments to a specific crop (which university budgets do not typically do) was that if bad things happen to an individual crop, then there is a built in offset for that crop's poor performance that should be taken into account when considering the economics of any individual crop.    I can understand arguments for and against.   But I tend to prefer allocating the wheat title to wheat, and the corn title to corn etc.   But I could see the alternative argument and just calculate the total payments and allocate them by planted acres -- thereby disconnecting the title payment from the crop.   

I wonder for you if the path of least resistance and would require the least reworking of the model is staying with the current/original approach of allocating title payments to the crop column.   I think we should consider showing all the columns even if there are no planted acres to that crop.   The detailed budget format would always be the same as the farmer tested and printed off various cases  and if he zerod out a crop it the column would appear but just show zeros.    One way technically to do this, would be in a case of zero planted acres for a crop, we could force zero to be a very very small non-zero number.  Like .0000000000000001 acres.   That way the column would always appear, the title payments for any crop would show up in that crop's column.  That might actually be the path of least resistance in terms of model design also?   Just a thought for discussion.  I do think the max number of columns for any farmer in the US. would be 4 columns which is the format we have for Grandview farm.   That Grandview format is busy but not too onerous, and it can be printed off on one page and will look fine once we finalize the final formatting and fonts.    Let's both noodle on this some more and perhaps talk early next week.

**Comment by KelleyDrake** [comment]
I moved the conversation from e-mail over to where it should be on Github.   Please see my thoughts and comments there.

**Comment by ddrake** [comment]
I think this issue is closely related to #51 and should be resolved once that issue has been resolved.
