### ISSUE TITLE
FSA caps do not appear to be working - see sensitivity table on my Marquis Farm case

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#50]
When I go to the Grandview Farm model, I have 3 FSA caps (which would limit payments to a total of $125k x 3 = $375k.   But when I look at the sensitivity analysis for Title payments for the Farm, it is showing dollar amounts well in excess of that.   If you go back to my simplebudget tool, the total payments are limited to the cap.   Somehow that logic is not working anymore in IFBT.  

If calculated payments were to exceed the cap, then they are pro-rated by down and allocated to each crop.  For example, if calculated payments for a given sensitivity case after sequester deduct but before imposing any cap was $500k for corn,, $300k for beans and $50k for wheat for a total of $850k after sequester that would exceed the $375k total farm cap.   In that instance, my model   would pro-rate each of the three payments down such that corn $500k would equal $500k x ($375k/$850k) = $220.5k , beans would equal $300k x ($375k/$850k) = $132.4k and wheat would equal $50k x ($50/$375k) = $6.7k.   So the $375k cap would be imposed and the total $375k in payments allocated to each of the three crops.

**Comment by ddrake** [comment]
Fixed now.
