### ISSUE TITLE
Title Sensitivity Tables by Crop - Decision tool for Farmers

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#51]
In our current IFBT model, we will eliminate the crop level title sensitivity analysis and retain only the Whole Farm sensitivity presentation.   When it is feasible, we should replace the remaining Whole Farm sensitivity output table and add three crop specific sensitivity tables, one for each of corn, beans and wheat.    The eliminated crop level sensitivity analysis did not provide the farmer with a decision tool to help the farmer see the payments under ARC-Co or PLC for each crop or allow the farmer to compare payments and make better choices to maximize title payments for each crop.   The new sensitivity analyses, when implemented, will allow the farmer the ability to see the implications for each crop (corn, wheat and beans)  of a choice of ARC-Co or PLC.  In the IFBT google drive, I have put an excel file "mock up" of the format for the four suggested sensitivity tables for each of  Whole Farm, Corn, Wheat and Beans.   That excel file is called "Revised Title Sensitivity Suggested Format".  I offer two alternative presentations for "Whole Farm" - one containing more detailed information and one containing less information.   We can decide later upon which of those two formats we prefer.

**Comment by ddrake** [comment]
Either the temporary fix (eliminate the crop-level title sensitivity analysis) or the desired solution in the mockup will be implemented by November.  For the moment, though, I'd prefer to do nothing.  Here's why:

Both the temporary fix and the desired solution will require some thought about the user interface and possibly a redesign.  For example, suppose the user selects 'DC Beans' for the crop.  The Title option would then not be available in the 'type' selector (even in the desired solution) since the only available options would be the FSA Crops (typically 'Corn', 'Beans' and 'Wheat').  Having 'type' options appear and disappear could be confusing to a user.  A better solution might be to remove the 'Title' option from the 'type' selector and add a third selector, just for Title, which would have options: the user's FSA Crops and  'Farm'.  If any of these options was selected, the selections for the 'crop' and 'type' selectors would be cleared, and if a 'crop' or 'type' selector was set to an option, the new 'Title' selector would have its selection cleared.

**Comment by KelleyDrake** [comment]
I don’t follow exactly. But I think your suggestion of leaving things as is is fine for now.

I think what we are saying in the sensitivity tables as they appear now, is simply the grand total farm title limited by total FSA cap divided by the farmed acres for each crop.   If you go to the corn sensitivity, for example, that has nothing to do with the payments made based upon corn title decisions (ARC-CO or PLC) and corn specific price/yield factors.    Instead, that is simply the total of all payments  (corn, wheat, and beans) allocated by planted acres.

You are absolutely correct that the farmer’s title decisions and payments are completely unrelated to whether a crop is planted or how many acres are planted.   So if I am understanding you correctly, I agree that Title choices inputs and outputs should be entirely separate from crop selections and all those related inputs and output.

I’m not positive about this.   But I think that if the Farmer didn’t plant anything at all on his cropland, he would still receive title payments if any were triggered for his corn, beans and wheat acres based upon the selected program for each.   So you could conceivably have title income and not have ANY crop to put it in (in this edge case).   I don’t think this case is something we should worry about, as if the farmer is doing a budget, he must intend to plant at least one crop.    So, for example if he plants one crop (Corn), then all title payments (for any combination of ARC-Co and PLC payments for corn, beans and wheat) would get allocated to that single corn crop.

Not sure if I’m being clear or not.   But OK to leave things as is for now.   But I do think that the changes that I proposed this morning will allow the farmer to have an ARC-CO, PLC decision tool and see the implications by individual crop of choosing ARC-CO or PLC would provide much greater value to the crop specific sensitivity tables.

But that can all wait for later.

**Comment by KelleyDrake** [comment]
Dow,

I just uploaded an edited version of my long word document describing the sources of data and how the model works to the IFBT google drive.   Cleaned it up a lot, eliminated a lot of redundancy, and I think made it shorter and clearer.   Nothing new for you to review – but just wanted you to know that a “better” version was up on the drive.   I will keep cleaning up and adding to it as appropriate as things arise.

Best
Kelley

**Comment by ddrake** [comment]
I believe the upshot of this discussion to create a Title sensitivity tool based on Kelley's [Revised Title Sensitivity Suggested Format](https://docs.google.com/spreadsheets/d/1jJyCh7jCj0625_tLkH8HfJdz3EyYJAv-/edit#gid=85469281), but I think we decided to use pre-sequestration values in $/acre.

**Comment by ddrake** [comment]
Since this decision tool has the same basic format as the sensitivity tables, I think it should be accessed through the same page, just as a separate option in the drop-down list.  I don’t think a diff would be appropriate.  Not sure if we need a separate one for each FSA crop.

**Comment by KelleyDrake** [comment]
I think we can drop this additional feature request.    We can use the tool as is as a decision tool.   Just need to do title choices do one crop at a time.   I showed that in one of the final videos.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 9/12/23 9:01 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Title Sensitivity Tables by Crop - Decision tool for Farmers (Issue #51)


Since this decision tool has the same basic format as the sensitivity tables, I think it should be accessed through the same page, just as a separate option in the drop-down list. I don’t think a diff would be appropriate. Not sure if we need a separate one for each FSA crop.
