### ISSUE TITLE
County DC Bean Yields

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#55]
Farm and County DC Bean yields are each input items on the Farm Crop Budgets page.   

Recall though that for County based policies and ECO and SCO, the RMA does NOT report two separate County yields (one for FAC beans and one for FS beans).   Rather they report only ONE combined number for FAC and FS Beans.      While there is no problem having/showing County FS Yields and FAC yields on the input page (for consistency in the presentation), we cannot use that the County DC bean yield for purposes of any indemnity calculations -- in fact that County DC bean yield should not be used for anything.    

Rather when we calculate indemnities for Area (County) insurance and ECO and SCO, for BOTH FS and DC beans, I think we should make a simplifying assumption and treat the County FS bean yield (that appears in the Farm Crop Budgets box) AS IF it is also the total County Bean yield.   And when that yield is sensitized, that is the yield that is used to calculate indemnities against the Benchmark County Yield.    For example, if you go into the 2023 crop year RMA actuarial tool, you will find that the Benchmark County Yield for Soybeans in Madison County is 56 b/a.    There is not a higher FS benchmark and a lower DC benchmark.   They provide us with only one benchmark yield.    

Right now, in the model, we are incorrectly overstating indemnities for DC beans Area (county) coverage and ECO and SCO for DC beans because we are using the low County DC bean yield (from the Farm Crop Budgets Page) and comparing it to the much higher single County Benchmark yield.

**Comment by ddrake** [comment]
For now we weight county fs and dc 90%-10%

**Comment by KelleyDrake** [comment]
About half the counties we support have FAC Soybean practices.   About 5% of total soybean acres in the US are Double Crop.  So if half the counties do no DC and half the counties DC, then overall that would support our estimate of 90% 10%.   That said, if you look at the link below, you'll see that various states have substantially higher or lower DC acres as percent of total acres.  Another approach would be to use the farmer's own split of acres to weight FS % and DC %.   For example, for Grandview, we will have 408 DC bean acres (11%), 3,319 (89%) FS bean acres for a total of 3,727 Toal Bean acres.  Maybe that is the way to go?   For farmers where DC bean insurance is available and where they planted no DC beans, we would not have a column for DC beans.   Therefore when we estimate county yields for that case, we would, by default, be using 100% FS County yields as the County yield estimate anyway.   If we went my suggested route, we'd basically be saying the farmer's DC/FS mix equals the County's and vice versa.   For Counties where there are a LOT of DC beans as a percent of total and where a straight 90/10 split might be too low, the farmer's own mix which might be well higher than the 10%  and we could then use that higher percentage?   For further discussion.   I'm OK with either approach, but kind of prefer using the farmer's allocated bean acres as a proxy for what the County allocated of DC/FS bean acres would be.  

https://www.no-tillfarmer.com/blogs/1-covering-no-till/post/11628-less-than-5-of-us-soybeans-are-double-cropped#:~:text=The%20double-crop%20acreage%20has%20fluctuated%20around%20the%204-million-acre,from%2010%25%20in%202013%20to%20only%204.6%25%20today.

**Comment by ddrake** [comment]
I like the idea of using the farmer's actual FS/DC split to determine the estimate for weighted county yield.  That keeps the implementation and documentation simple and, as you say, maybe gives a better estimate.  Here are some other thoughts:

> As a percentage of total soybean acres, Virginia led with almost 39% of its soybean acres being double-cropped. Oklahoma, Georgia and North Carolina also topped the 30% threshold. 

- Interestingly, Virginia, Georgia and North Carolina _only_ have crop insurance practices irrigated and non-irrigated beans.  FAC/NFAC are not distinguished for these states in the RMA insurance offers, so DC Beans would not appear as a farm crop in our application.
- I suspect that that counties that have a *higher percentage* of dc soybean acres also have *narrower yield differences* between full and dc beans.  If that is the case, the percentage won't matter much.  I can check that hypothesis  by looking at 2021 or 2022 RMA final county yields for some of these states (e.g. Oklahoma) with wider splits.

**Comment by KelleyDrake** [comment]
That is interesting and a little weird.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/27/23 3:11 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] County DC Bean Yields (Issue #55)


I like the idea of using the farmer's actual FS/DC split to determine the estimate for weighted county yield. That keeps the implementation and documentation simple and, as you say, maybe gives a better estimate. Here are some other thoughts:

As a percentage of total soybean acres, Virginia led with almost 39% of its soybean acres being double-cropped. Oklahoma, Georgia and North Carolina also topped the 30% threshold.

  *   Interestingly, Virginia, Georgia and North Carolina only have crop insurance practices irrigated and non-irrigated beans. FAC/NFAC are not distinguished for these states in the RMA insurance offers, so DC Beans would not appear as a farm crop in our application.
  *   I suspect that that counties that have a higher percentage of dc soybean acres also have narrower yield differences between full and dc beans. If that is the case, the percentage won't matter much. I can check that hypothesis by looking at 2021 or 2022 RMA final county yields for some of these states (e.g. Oklahoma) with wider splits.

**Comment by ddrake** [comment]
It's weird, but true.  I just added a new farm year in Virginia -- no DC beans!

By the way, I noticed I'd broken the Add Farm Year form recently, but it's fixed now.
________________________________

**Comment by ddrake** [comment]
It might not be a bad idea for you to check this at the RMA site if you get a chance, i.e. see if you can insure DC beans in Virginia, just in case I messed up something in the big RMA data import.
________________________________

**Comment by KelleyDrake** [comment]
Will do



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/27/23 4:50 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] County DC Bean Yields (Issue #55)


It might not be a bad idea for you to check this at the RMA site if you get a chance, i.e. see if you can insure DC beans in Virginia, just in case I messed up something in the big RMA data import.
________________________________

**Comment by KelleyDrake** [comment]
I just checked a whole bunch of counties in Virgina and none of them have FAC soybeans.   There are LOTS of specialty varieties and practices (eg. large seed food, small seeded food, low lyn, low saturated fat, high protein, organic with many of those both irrigated and non-irrigated).    But not seeing a FAC practice for any county in Virgina.    Strange that the article says double crop is so high a percentage but they don't seem to have government crop insurance program set up for it.   Maybe it has something to do with all the specialty crops?    Not sure.   FYI I only have DC bean budgets from universities for IL, KS, MO, MS, AR, TN, AL, and MD.    Based on my check of Virgina, I don't have any evidence to suggest that the data came in wrong.

**Comment by ddrake** [comment]
Thanks -- that's great.   Another possibility is that dc beans are just merged with full season and reported as "beans" in those states.

**Comment by KelleyDrake** [comment]
A lot of the tickers are needed for the MYA calculation prior to the first May Wasde release.   Since we lapsed that first Wasde date, I would expect fewer to be required now and going forward.

We still need all the harvest futures used for crop insurance harvest discovery --- and then, once those expire we will need the 2024 July contacts.

 I do think at some point across the entire crop year, every one of those tickers will be used.   But not all are needed for every model run date

Hope that makes sense.

Best
Kelley



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/27/23 6:10 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] County DC Bean Yields (Issue #55)


Thanks -- that's great. Another possibility is that dc beans are just merged with full season and reported as "beans" in those states.

On a totally different subject, I was working on adding the contract expiration dates you looked up and noticed that we're collecting futures prices for 31 tickers, but I'm not sure how they're all being used. 7 of the tickers are used in the "County Crop Types and Ins Dates" tab of the simplebudgetmodel, which is in the database as table 'ext_insurancedates' and I think about 5 of them are July contracts in the year after harvest, but I don't think I'm using any of the others.

It's fine if there are extra prices, but I just wanted to find out if I'm missing something.
________________________________

**Comment by ddrake** [comment]
Ok thanks- I’ll take another look at the pre-wasde rma calcs.

Sent from my iPad

On Jun 27, 2023, at 4:24 PM, KelleyDrake ***@***.***> wrote:

﻿

A lot of the tickers are needed for the MYA calculation prior to the first May Wasde release. Since we lapsed that first Wasde date, I would expect fewer to be required now and going forward.

We still need all the harvest futures used for crop insurance harvest discovery --- and then, once those expire we will need the 2024 July contacts.

I do think at some point across the entire crop year, every one of those tickers will be used. But not all are needed for every model run date

Hope that makes sense.

Best
Kelley



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/27/23 6:10 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] County DC Bean Yields (Issue #55)


Thanks -- that's great. Another possibility is that dc beans are just merged with full season and reported as "beans" in those states.

On a totally different subject, I was working on adding the contract expiration dates you looked up and noticed that we're collecting futures prices for 31 tickers, but I'm not sure how they're all being used. 7 of the tickers are used in the "County Crop Types and Ins Dates" tab of the simplebudgetmodel, which is in the database as table 'ext_insurancedates' and I think about 5 of them are July contracts in the year after harvest, but I don't think I'm using any of the others.

It's fine if there are extra prices, but I just wanted to find out if I'm missing something.
________________________________

**Comment by ddrake** [comment]
Implemented county yield for soybean indemnity as sum(fs_acres\*fs_county_yield + dc_acres\*dc_county_yield).
