### ISSUE TITLE
User should not be allowed to choose County (Area) coverage and ECO

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#56]
In the Farm Crops input page, the user can select Area Coverage and then add ECO on top of that.   SCO is appropriately not available to the user, but ECO is available and should not be.   Both ECO and SCO have to be stacked on top of a Farm Based policy (and not an Area (County) based policy.

**Comment by ddrake** [comment]
Got it -- should be an easy fix.

**Comment by ddrake** [comment]
Implemented and tested locally, should be working at the live site now.

**Comment by KelleyDrake** [comment]
Great!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 6/27/23 3:23 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] User should not be allowed to choose County (Area) coverage and ECO (Issue #56)


Implemented and tested locally, should be working at the live site now.
