### ISSUE TITLE
Allow users to finalize farm yield for individual crops

### ISSUE THREAD

**Issue by ddrake** [ddrake/Integrated_Farm_Budget_Tool#74]
A possible implementation:
* Add a date field `farm_yield_final_on` to farm_budget_crops
* Change the farm_budget_crop update form, adding a checkbox `farm yield final".  If the user checks this, two things happen:
    * The `farm_yield` field becomes locked for edit.
    * On saving the forrm, the `farm_yield_final_on` date value is set to the current date.
* If the user later unchecks the box, the `farm_yield` becomes editable again and on saving, the `farm_yield_final_on` date is cleared.
In the model, we modify the `sensitized_farm_yield` function to check the model_run_date against the `farm_yield_final_on` date.  If it falls after it, we return the `farm_yield` value with no sensitivity applied, otherwise we apply the sensitivity factor.

We probably need to think more about how to handle the row and column headers in the sensitivity table, but I think this should take care of the bulk of the issue.

**Comment by ddrake** [comment]
Comment from Kelley in issue #76
For our sensitivity tables, I think that when a crop yield goes final we stop Sensitizing that yield by the yield sensitivity factor and add some sort of note that shows that that crop yield is final. So for Grandview now that wheat is final and Corn, FS Beans and DC beans are not final, the sensitivity page would look the same but wheat yields would not change by the yield factor and the other crops would continue to change based on the yield factor. Suggest we add a label next to wheat yields in the presentation over the top of the sensitivity page to indicate that wheat yield is final. And when others go final, they too are relabled as final and no longer sensitized.

**Comment by ddrake** [comment]
I ran into a snag with the final wheat yield.  I set the wheat yield to 105 and marked it final, but the costs still changed with yield factor because of the yield adjustment to nonland costs.  So I put in some code that calculates that yield adjustment using the _yield factor_ if model_run_date is before farm_yields_final, but using the _ratio_ of farm_yield/baseline_yield_for_var_rent otherwise.  If you have a better idea, please let me know.

**Comment by ddrake** [comment]
If the user adjusts farm yield after harvest, they should also adjust county yield.  Locking now locks both farm yield and county yield.  Time travel will not work as I'd hoped, so I removed the underlying date field.  I added a similar feature for costs, so that once final costs have been added, the yield-based adjustment becomes zero.

**Comment by ddrake** [comment]
@KelleyDrake is testing a time travel session.  This can be closed unless issues arise.

**Comment by KelleyDrake** [comment]
I did some testing on the locking yield when known and locking costs.   Everything working great.   I understand it and it makes perfect sense to me.   Very nice!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 7/4/23 7:37 AM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Mention ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Allow users to finalize farm yield for individual crops (Issue #74)


Closed #74<https://github.com/ddrake/Integrated_Farm_Budget_Tool/issues/74> as completed.

**Comment by ddrake** [comment]
Thanks! -- that's good to hear.  The caching issue took me a long time to debug -- sorry for the delay...

________________________________
