### ISSUE TITLE
Model Broke on Me

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#75]
I was doing a demo for a friend and the model broke.   I think it relates to selection of budgets.   I now have two farms, Marquis (Grandview) and Peter's Farm in Indiana.   I first was in Marquis farm and to show how the budgets come in from the library, I selected a different wheat budget than the one that was there.   That broke the Marquis Farm model.   I then tried to build a new farm in Indiana.   It has a similar problem and I could not get to any output pages.    I'm getting an error message when I try to run the detailed budget and the sensitivities.

**Comment by ddrake** [comment]
Fixed in commit [68423](https://github.com/ddrake/Integrated_Farm_Budget_Tool/commit/684238743ea603cf0a01a8282616f6536cadba3c)
