### ISSUE TITLE
Sensitivity Tables Once Yields Go Final

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#76]
For our sensitivity tables, I think that when a crop yield goes final we stop Sensitizing that yield by the yield sensitivity factor and add some sort of note that shows that that crop yield is final.    So for Grandview now that wheat is final and Corn, FS Beans and DC beans are not final, the sensitivity page would look the same but wheat yields would not change by the yield factor and the other crops would continue to change based on the yield factor.   Suggest we add a label next to wheat yields in the presentation over the top of the sensitivity page to indicate that wheat yield is final.  And when others go final, they too are relabled as final and no longer sensitized.

**Comment by ddrake** [comment]
I added the above comment to issue #74 since this is very closely related.  Closing this.
