### ISSUE TITLE
Server Error 500 and Bad Gateway Error 502

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#82]
You may be currently working in the model which might explain this.   But as I was going through the steps to build my Demo farm, I got hung a few times with the errors listed above on Farm Crop budget and Sensitivity Tables.   Then I went through it again and I did not get those same errors.   So a little wierd.   Just FYI.

**Comment by ddrake** [comment]
Pretty sure the application server (gunicorn) was in process of restarting when that happened.

**Comment by KelleyDrake** [comment]
All good.   Excellent stuff!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 7/3/23 7:19 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Server Error 500 and Bad Gateway Error 502 (Issue #82)


Closed #82<https://github.com/ddrake/Integrated_Farm_Budget_Tool/issues/82> as completed.
