### ISSUE TITLE
Dashboard Suggested Changes

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#86]
On dashboard I'd like to suggest we make the titles a little more descriptive and logical.

The first line shows "Demo Farm (2023 Crop Year) in Summit, County OH.   I think that can be shortened to Demo Farm (2023 Crop Year). 

The next line has two input pages: "Farm Crops | Farm Crop Budgets"   Since "Farm Crops" section is mostly crop insurance, I would suggest renaming that to "Crop Acreage Allocations and Crop Insurance". 

 I'd move the second input page called "Farm Crop Budgets" to its own line immediately below and call it "Crop Yield and Expense Budgets".    I think it deserves its own line and this is a better descriptor of what it is.  (as budgets implies a full budget from topline revenue all the way down to profit -- and this does not include the revenue part of the equation.  

I'd suggest changing the title "Market Crops" to read "Grain Marketing Assumptions".   I'd change "FSA Crops" to read "Title Elections: ARC-CO/PLC".   I'd separate "Detailed Budget" and "Sensitivity Analysis" so that each had their own line. 

So once a farm is created it would have a Dashboard once a Farm is named, state and county are added:

Demo Farm (2023)         (With this line being just an identifier title line- and not a live drop down page
Inputs:
      Farm Specific Data
      Crop Acreage/Crop Insurance
      Yield and Expense Budgets
      Grain Marketing
      Title Elections:  ARC-CO/PLC
Outputs:
       Detailed Budget
       Sensitivity Analysis

I think those changes might make the Dashboard more descriptive and intuitive.  But obviously open for discussion. 7 total sections with 5 Input Sections and 2 Output sections.

**Comment by ddrake** [comment]
I agree this would be good.  I think we still need a page where the user can see all their farm years and add a new one.  Maybe we call that the "Farm Years" page.  I think this is where a user is directed after logging in.  This page could simply have a list of links for all existing Farm Years (probably including the state and county in the link text) and a button to add a new Farm Year.  Then clicking a link for a specific farm year would bring up the Farm Year-specific dashboard you're describing.  Does that make sense?

**Comment by KelleyDrake** [comment]
Yes.  Can't visualize exactly but conceptually sounds right.

**Comment by ddrake** [comment]
Done!

**Comment by KelleyDrake** [comment]
Sweet!



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Dow Drake ***@***.***>
Date: 7/6/23 12:57 PM (GMT-06:00)
To: ddrake/Integrated_Farm_Budget_Tool ***@***.***>
Cc: ***@***.***, Author ***@***.***>
Subject: Re: [ddrake/Integrated_Farm_Budget_Tool] Dashboard Suggested Changes (Issue #86)


Done!
