### ISSUE TITLE
Changes to the Layout of what is now called Farm Crops Tab

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#87]
From my additional reading, the very good news is that what we are now calling "TA APH yield" is the yield that we should be using for indemnity purposes.   However, that input line should not read "TA APH yield" but rather be retitled "Approved Yield".

I think we may have a nomenclature issue that I'd like to explain.   I think Rate Yield and Adjusted Yield are two numbers that are calculable for each farm based upon its planned crop acreage allocation and past yield history -- and not dependent upon any selections like TA or YE.   A farmer is best served if he tries to maximize his "Approved Yield".   In doing so he selects TA and/or YE.    These selections in most situations will produce "Approved Yields" that are higher than "Adjusted Yields".    So what we are now calling "TA APH yield" and using for the benchmark yield for crop insurance should really instead be called "Approved Yield".    

 I think what happens is the farmer and crop insurance agent have the first two yields (Rate and Adjusted) that fall out of the farm's yield history.   They then select among the various choices of TA and/or YE.  These choices will produce different Approved Yields depending on the underlying yield circumstances.    Almost always the farmer/crop insurance will choose TA which will increase the "Approved Yields"   I think the farmer will almost always choose YE also - although YE may not always be available or have any effect.   At any rate they work together to find the combination of choices that produces the highest "Approved Yield".   

So when we ask the farmer the question about yields, I think we change the order and lines to make this somewhat more clear.   I'd suggest we move what is now called "Trend Adjusted APH yield" down several lines to underneath "Use yield Exclusion".   I think this will help make clear that the choices of TA and YE selections shown above will produce a different Approved Yield result.    And we rename "Trend Adjusted APH Yield" to "Approved Yield".    And then we continue to use that now renamed "Approved Yield" input cell for the benchmark for indemnity calculations.

If both TA and YE are turned off, then "Approved Yield" should, by default, equal Adjusted Yield (from what U of I says).  We could therefore force "Approved Yield" to equal "Adjusted Yield" under that one scenario (no TA and no YE) if we wanted to keep the farmer from messing up.   Your call if you want to add that additional protective logic to the code.  Unless easy, I wouldn't bother with it. 

So at the end of all this "issue" I am suggesting that we move one line down and rename it!   That's all!

**Comment by ddrake** [comment]
So if a user's "Approved Yield" based on choices of TA and/or YE is obtained from their crop insurance agent and entered, can we also safely use that number in the *premium* calculation in place of TA APH Yield, assuming that they select the same choices of TA and/or YE in our application?

**Comment by KelleyDrake** [comment]
I think it has to be.  Yes.   I think the confusion is that TA APH yield is being used synonymously with Approved Yield because it almost always is the same thing.

But one could hypothetically compute a TA APH but then not use it by turning off TA or YE.   That would be a mistake for the farmer to not use TA or YE.   But he could say no "I don't want to use those as it increases my insurance costs" and then suffer from using the much lower Adjusted Yield as his "Approved Yield" for indemnity benchmarking.

I think the vast vast majority will choose to use TA and YE and pay the higher premium rate to get the higher benchmark "Approved Yield"

**Comment by ddrake** [comment]
Ok then I'll proceed with the name change
