### ISSUE TITLE
Super Minor Edit to the Main Landing Page

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#90]
Suggest we change my language to make it a little more direct and more punchy.   

Replace my prior language.....   "Helping farmers across the U.S....." with
 
VISUALIZE RISK  |  MANAGE RISK  

In all caps, a pretty large font, and beneath the title "Integrated Farm Budget Tool"

**Comment by ddrake** [comment]
Done!
