### ISSUE TITLE
Minor suggested title edit on Farm Year page

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#91]
Suggest we change title from "FAC acres" to "Double Crop Acres"   Same thing but I think a tiny bit clearer for the reader.

**Comment by KelleyDrake** [comment]
Actually I'd suggest this instead.   This will be crystal clear for the user.

Full Season Planted Acres
Double Crop Planted Acres
Total Planted Acres

**Comment by ddrake** [comment]
Done!
