### ISSUE TITLE
Very Minor issue on suggested rounding on Marketing Page

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#92]
Suggest rounding acres and bushels to no decimals (e.g. planted acres, expected bushels, bushels basis).  And rounding all prices including basis to two decimals places (e.g. Average contract price, average locked basis, assumed basis, recent price).   I think it will help clean up the page and make more visually consistent and intuitive.

**Comment by ddrake** [comment]
Done!
