### ISSUE TITLE
Worried that Title Calculations May Not Be Working

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#93]
I am noticing that all numbers in the title payments section are either zero or the maximum available to the farmer based upon their caps.    I would have expected to see title payments start to "kick in".  And we would in certain circumstances payments  that are above zero but below the maximum.   It seems that everywhere, always the payments are either zero or the maximum.    I also think that both ARC-CO and PLC have caps in their underlying programs that come into play independent of the Farm's FSA caps.   These program caps on $/acre payments would normally kick in well before the FSA caps would come into effect for smaller farms.   Only quite large farms would every get payments that would exceed $125k.

**Comment by KelleyDrake** [comment]
There are two important things that are not calculating correctly for Title.   Each program has its own internal maximum payment rates.   ARC-CO plc has a maximum payment rate calculation which is in simplebudget tool and on the FSA excel spreadsheets.  For example in Summit County OH, the maximum payment rate for ARC/PLC is $48.16/acre for corn, $36.40 for beans and $31.90 for wheat.   In current Demo model I have assume title acres of 245 corn, 245 beans and 20 for wheat.   Recall that these are BASE ACRES and have nothing to do with PlANTED ACRES.   So the maximum this farmer could receive putting all bawe acres into ARC-CO PlC payments is $11,799+$8,918+$638 =$21,355.   Just to test what our model is doing, I put in 10 FSA entity caps.   You'll see in sensitivities that we've got this farmer receiving $1,250,000 in title payments (10 x $125) where the total maximum payments for this farmer should be $21,355 * (1 - .062 sequester) = $20,031.    No FSA entity cap would come into play as this is well below even one entity cap at $125k.

 PLC has its own internal caps and the Payment Rate cannot exceed the Effective Reference Rate - National Loan Rate.  For Corn Effective Reference Rate is $3,70, National Loan Rate is $2.20 and therefore max PLC payment Rate equals $1.50/bushel.  The Bean Max payment rate is $2.20/bushel and wheat maximum payment rate is $2.12 per bushel.    To get to maximum PLC payments for the Farm we would take the (245 corn base acres x 85% x 160 PLC yield) = $33,320, plus (245 bean base acres x 85% x 45 PLC yield) = $9,371 plus (20 wheat base acres x 85% x 55 PLC yield) = $935.   $33,320 + $9.371 + $935 = $43,636.   We apply the 6.2% sequester and get a $40,930 maximum payment before FSA entity cap.   No FSA entity cap would come into play as this maximum payment is well below even on entity cap at $125k.  When I put all the base acres into PLC, the calculated total farm title payments that the farmer is receiving is $1,250,000 in payments!   And not the MUCH lower $40,930 max that the farmer should be getting paid.   

Perhaps this should be a separate issue but I will mention this here (as I think it may be related).  In my model I have no PLANTED acres of wheat for the Demo farm.   If you go to the Title input page and look at the section called Program Specific Title Information and look in the wheat column, you will see that "benchmark county Yield" is show as $0.   This should be $319.00.   I'm not sure the error here and why that is not coming in from the FSA title database.   Perhaps it is because we have no PLANTED wheat acres??   However, No PLANTED wheat acres should not affect title at all, as the only thing that matters is base acres.   Not sure that this is the reason that the $319 benchmark county revenue for ARC-Co is not coming in.... but just speculating that might be the case?

**Comment by ddrake** [comment]
The county benchmark revenue is showing zero  because with the current weighted averaging approach (weighted by planted acres), I have a fallback to prevent dividing by zero.  I think that there may be a better way.  This really should be at the FSA Crop level anyway.  I'll move it there.  The only problem is the irrigated status.  Instead of a weighted average over planted acres, if there are multiple farm crops with planted acres, I'll use the irrigated status of the one with the most planted acres.  If there is only one farm crop associated to the FSA crop, I'll use its irrigated status even if its planted acres are zero.  How does that sound?

**Comment by ddrake** [comment]
Thanks for the examples on the max payment rate capping.  That should help in troubleshooting that aspect of the issue.

**Comment by ddrake** [comment]
The county benchmark revenue should be correct for your Demo farm now.

**Comment by KelleyDrake** [comment]
Not exactly following this.

Your point about this being title and having nothing to do with planted acres makes perfect sense to me.

With respect to irrigated or non irrigated which applies only to ARC-CO, I think if a farmer selects irrigated for one crop (say corn) planted acres then we assume that the entire county is irrigated for that crop and then we use the irrigated Arc-CO county benchmark revenue line from the FSA spreadsheet.

 If he plants non-irrigated corn, we assume the county is entirely non-irrigated and use the non-irrigated ARC-Co benchmark revenue line from the FSA database.

  If he does not plant any acres (and therefore we have no view as to the county), I think we should just default to Non-irrigated county benchmark revenue as that will be by far the most common practice nationally.

 So in my example, where the Ohio farmer plants no wheat, we should grab the FSA county benchmark revenue for non-irrigated wheat.   As long as we are showing that benchmark county revenue number on the screen, at least people will know what we are doing behind the scenes.   Does that make sense?

**Comment by ddrake** [comment]
I can do it that way.  But we also need to handle the case e.g. 1000 acres irrigated fs beans 300 acres non-irrigated dc beans.  In that case, I'm proposing we say it's irrigated, because most of the bean acres are.

**Comment by ddrake** [comment]
County benchmark revenue is managed in fsa_crops now, irrigation status is determined as follows:
- if there are no planted acres for any of the fsa_crop's farm_crops, the fsa_crop's status is 'non-irrigated'
- otherwise, we find the farm_crop in the fsa_crop's set of farm_crops with the maximum planted acres, and set the irrigation status of the fsa_crop to that farm_crop's irrigation status.

Commits 4558c9f and 342947f.

Do you have a preference in the unlikely case there is a tie?  e.g. 500 acres fs irrigated beans, 500 acres dc non-irrigated beans.

**Comment by ddrake** [comment]
Please check the sensitivity table again.  As you may have suspected, the code in main.gov_pmt was multiplying the pre-sequestration title payments (already in dollars) by fsa crop planted acres.  A dumb mistake that's been there for awhile.  
See commit 56188a1
Closing this issue, but feel free to re-open it or start a new issue if you think any values are incorrect.

**Comment by KelleyDrake** [comment]
I am fine with that.  Makes sense

**Comment by KelleyDrake** [comment]
In a tie I would suggest non-irrigated.

**Comment by KelleyDrake** [comment]
Will do the checks!  Thanks!

**Comment by KelleyDrake** [comment]
I am now seeing much more sensible title numbers.  But something still is not right as there are title payments being made in every sensitivity combination ofbprice and yields for ARC-Co.  These should only kick in in situations in which county revenue falls below county benchmark revenue.   At high prices and high yields there will be no payments.   I'll check PLC next.

**Comment by KelleyDrake** [comment]
Plc looks like it is working.  Need to double check the math and see which crops are triggering but this looks right.

**Comment by KelleyDrake** [comment]
We calculate the total title payments for corn, beans and wheat using the sensitivity factor.   Then divide them up based on planted acres.   In my example I have no planted acres to wheat.   Now when I do the title sensitivity I get what I think is likely correct (need to check) for corn and FS Beans.   But when I check whole farm sensitivity I am getting a $1k payment minimum in all cells, even those where no payments should be made.  If we're to hazard a guess, is it possible that this has something to do with no wheat planted acres?   Not sure but there would not be any payments at high yields and prices for corn, wheat and beans.

**Comment by KelleyDrake** [comment]
Here is an interesting question.    In the event that a farmer plants no wheat but has base acres I presume whole farm sensitivities would impact on county yields and mya prices for wheat (even with no crop)   if a farmer (or I) wanted to run a specific case to see if wheat title payments would be made (and where if there were planted acres the user would set those price and yield sensitivities) given that we have no planted wheat I don't think we have a place to input those speific price and yield volatilities for wheat.   Since no planted wheat we'd not have a place to set those price and yield factors.

**Comment by KelleyDrake** [comment]
Dow,

I ran a test on Title on my Demo Ohio farm.  I tried to isolate a single case for corn and see what might be happening with ARC-Co payments and see if it is working.    I will leave my demo farm set up like what I describe below so that you can see what I am talking about.

I have 245 acres of corn title, 245 acres of beans title and 20 acres of wheat title.   I ran the corn crop (and only corn) at a 50% price factor and a 50% yield factor.  Beans and wheat have both price and yield factors set at 100%.  Therefore, I would expect an ARC-CO payment related to my corn base only and NONE to beans and wheat.

I am running the model on February 5, 2003.    The harvest price on that date was $5.96 and starting MYA price from that USDA MYA model was $5.81 (prior to first Wasde).  After the 50% price variability factor, the revised MYA price was $2.90 (which makes sense as at this point in the year price factor will impact MYA exactly proportionately to yield factor).   The starting farm yield was 181.8 and the starting county yield was also 181.8.   So the adjusted yield after the 50% yield factor for both farm and county was 90.9 b/acre.    Therefore, for the corn Arc-Co calculation, projected Actual County revenue for corn should equal 90.8 x $2.90 = $263.32/acre.   This is well below the county benchmark revenue of $481.58 and the 86% guarantee equal to $414.15.  Therefore, I would expect that the maximum amount of corn payments should be paid out.   The maximum payment rate is $48.16/acre (equal to 10% of the $481.58 of county benchmark revenue).   So I would have expected payments on corn base to equal $48.16 * 245 corn base acres = $11,799 before sequester and $11,067 after the 6.2% sequester.   Since I left bean and wheat price and yield sensitivity factor at 1.0 the corn payments should have been the ONLY title payments to be made.  Therefore, I would have expected the whole farm total payments to equal $11,067.   No "Entity" caps would apply since we are well below even one $125k cap (I still have my Demo model set at 10 entity caps).

Since I planted 250 acres of corn, 250 acres of beans and no wheat, I would expect to see the $11,067 of corn (the total farm payments) divided equally across the corn and bean acres and then shown in their associated budget columns in Detailed Budgets.   Therefore, I would have expected to see $5.5k in the corn budget and $5.5k in the bean budget columns.  Instead, I see zero $ in the corn budget, zero $ in the bean budget and 1K in the total farm budget column.   So something in the calculations appears to not be working.

Also If all three crops were set to low price and yield factors such that maximum payments would be made, those Maximum payments would equal (c $11,799+ b $8,829+w $638)=$21,266 or $19.948K after sequester.   When I look at the sensitivity table for whole farm title, in the very low price, very low yield cases where you'd expect to see that maximum payment, the value showing is $17k and not $19.9k.

**Comment by KelleyDrake** [comment]
I check Title for my same Ohio farm using PLC instead of ARC-CO for each.   That seems to be working.  I did the math and the payments shown in the sensitivity are exactly what I anticipated.   ARC-Co appears to be the only problem.

**Comment by KelleyDrake** [comment]
Stike my prior comment.   Wheat PLC payments do not appear to be calculated correctly.   In my Ohio Demo model I set wheat title to PLC,   I increased the wheat base acres to 100 from 20 acres so that I would definitily get a large enough $ result to have it show up in the detailed budget.   I set the price factor for wheat to 50%.  Starting estimated MYA at 100% factor was $8.17 so 50% of that equal $4.08.   That would produce a $1.42 price shortfall equal to $5,50 effective reference rate minus the $4.08 MYA price.   This $1.42 does not exceed the maximum PLC payment rate of $2.12 ane therefore the PLC payment will not be capped by this factor.    

 With 100 wheat PLC acres at a 50% wheat price factor I would anticipate the following Wheat title payment: 100 base acres x 85% x 55 PLC yield x $1.42 = $6.6k and $6.2k after the 6.2% sequester.   In my Demo model I have 250 planted acres of corn and 250 planted acres of beans.   So in my detailed budget, I would expect to see $6.2K/2 OR $3.1K  in each of the budget columns for Corn and Beans.  The detailed budget model, however, shows $0 PLC payments.   So if wheat payments are getting calculated correctly behind the scenes, they are not being aggregated and allocated to the budget columns based on planted acres.   I suspect this might have something to do with the fact that we don't have wheat planted acres??   But that should not make any difference as if a wheat PLC payment is supposed to be made, it should be allocated to the planted crops proportionately to planted acres.    I will turn the settings back to where they were for my ARC-CO test.  But this message provides you with a way to duplicate my test and see how the results are not coming through as expected.

**Comment by KelleyDrake** [comment]
I did another test of PLC payments for my Marquis Farm.  This one is not going back in time like my Ohio Demo.  But rather being calculated based off of the June Wasde report.   

At a 70% price factor simplebudgettool MYA logic produces Estimated MYA for corn of $3.61, beans $9.11 and wheat $6.31 (using the weighted average model logic in the post WASDE MYA calculation).  The effective Reference rate for corn is $3.70, beans $8.40 and wheat $5.50.   So only corn should trigger a payment equal to $.09/bushel.  This $.09 payment rate is below the maximum corn PLC payment rate.   I have 4,220 corn title acres x 85% = 3,587 payment acres and a 160 PLC yield.   Multiplying those together you get to $51.7k pre-sequester, $48.5k post sequester and no FSA entity cap is imposed.  So I would expect total farm payments to equal $48.5 instead of the $28k in total farm payments currently calculated by IFBT.

At a 60% price factor I get Est MYA of $3.22 corn $8.11 beans and $5.85 wheat.  All three title crops are triggered for payments ($.88 for corn, $1.29 for beans, and $.11 for wheat).   All of these fall below the maximum PLC payment rates.   Multiplying things out I get a total $332.6 pre sequester, $311.9 post sequester and $311.9 total (because we have a $375k, 3 $125k entity caps assumed).   At a 60% price factor IFBT produces $263k total farm payments and I get $311.9k.   I can provide more detail if that helps around the two calculations.   But the logic appears not to be working currently.  In both calculations (pre May WASDE and also post May WASDE).  I am manually computing these and believe that my math is correct.

**Comment by ddrake** [comment]
I fixed a number of issues on this, but I think there are still documentation and implementation issues:  
- I think we should update the wiki to advise users to add a budget for any crop that has nonzero PLC acres (because without a budget our only fallback for farm yield and county yield is approved yield, which might be zero by default for a non-planted crop.   
- I think the detailed budget should include columns for farm crops which have associated fsa crops with nonzero PLC yields and either nonzero PLC acres or nonzero ARC-CO acres. 

We should discuss all this...

**Comment by KelleyDrake** [comment]
Let’s discuss this. 

For PLC we do not need any County or Farm yields.   The only things we need from the Farm are number of title acres and the Farm’s average PLC yield from the 156 cards.   These are currently inputs on the Title Screen.   So I think we should be all set for PLC payment calculations.

For ARC-CO, however, we do need an estimated actual County Yield that we then sensitize along with MYA price to get to payments.   In situations where we have a farm budget and therefore have an estimated County Yield, we should be all set.   However, if one of the three title crops (corn, wheat or beans) is not planted and the farmer has title acres for all three crops, then we do need an estimated County yield.   For example, a farmer having title acres for each of corn, beans and wheat acres but not planting any wheat, we would need a Wheat County Yield.

To have a place to put this County yield, I’d suggest we add a line on the TITLE input page directly under PLC yield.    To populate this line for crops that we are planting, I’d suggest that we pull over the County Yield inputs for Corn and Beans from the Yield and Expense Input Page (and simply repeat them here…you can decide whether you want them editable or not here).   And where we’d have no number for Wheat County Yield, we’d REQUIRE the user to input a Wheat County Yield on this page.

That way you would not have to add the extra detailed budgets columns.  And we’d  have all you need to calculate ARC-CO and PLC payments in total for the farm.   We’d then apply the sequester and the FSA Entity Cap and take that Farm Total Title payment and divide by planted acres for each crop (just as we try do today).   In the Detailed Budget, we’d have only planted crops.   And each planted crop will have the identical ARC-CO PLC payment on a per planted acre basis.

Let’s discuss….. but I think that might be an easier way to solve the “We need a County Yield estimate for Wheat problem”.   I think that this would also be a more intuitive solution – I fear most farmer users will not know what a wiki is… or go out to use it.   So the more we can make things seamless on the actual series of screens that they see, the better off we will be in terms of useability.

**Comment by ddrake** [comment]
Closing this per phone call today.  Handled in Issues #102, #103 and #104
