### ISSUE TITLE
Getting Server Error 500 for Yield and Expense and Sensitivies tabs

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#94]
I was trying to test out my concerns over Title payments possibly not working.  So I changed my Demo farm from 1,500 acres down to a 500 acre farm, with 50/50 corn and beans.   When I tried to do that, I got Server Error 500 for both of the Yield and Expense tab and the Sensitivities tab.   Because of running into this error message, I was unable to check the title payments for a "small farm" as dicsussed in my prior issue.

**Comment by ddrake** [comment]
Fixed in commits d0a80d3, f168aa0 and 639bedd
