### ISSUE TITLE
On the Title Page we need to make FSA "entities" and estimated sequestration % both editable inputs

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#95]
The new form is good however it does not allow the farmer to edit the number of entities or the sequestration %.   I think those should both be editable inputs.

**Comment by ddrake** [comment]
I think those fields need to be edited at the farm year level, since they are not FSA crop-dependent.  I've added the sequestration % as an editable field there.

**Comment by ddrake** [comment]
Closing this for now.
