### ISSUE TITLE
Getting Server 500 Error

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#98]
I was creating a farm for the CGB demo (not set up yet).  I ran into Server 500 errors on the Detailed Budget screen and on the Sensitivities screen.   Just FYI.

**Comment by ddrake** [comment]
Thanks, I’ll figure it out tomorrow

Sent from my iPad

On Jul 11, 2023, at 9:39 AM, KelleyDrake ***@***.***> wrote:

﻿

I was creating a farm for the CGB demo (not set up yet). I ran into Server 500 errors on the Detailed Budget screen and on the Sensitivities screen. Just FYI.

**Comment by ddrake** [comment]
Fixed now.  A number of bugs were introduced by moving certain columns (e.g. yield_factor) from the farm crop model to the farm budget crop model.  These bugs surfaced in cases when farm budget crop models were not set.
